### ISSUE TITLE
hydration not working alongside server-only onCreate

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#1043]
### Details

@mlrawlings I'm using `onCreate` for server-only code to set the initial state of my component. As of `4.9.0`, the component does not get hydrated correctly, and `onCreate` gets fired in the browser. I can see this change was part of https://github.com/marko-js/marko/pull/1010, but I'm not sure if that missed use cases, or if I'm missing something.

If I comment out these lines (so that it goes to the `if(state)` part), everything works normally:
https://github.com/marko-js/marko/blob/7c5089b54c889cc8fc20c9f59eb0d591402e18b7/src/components/ComponentDef.js#L130-L137

### Expected Behavior

It seems that are some cases where `onCreate` should not be run in the browser, and instead the state should be taken from the serialization directly.

### Actual Behavior

`onCreate` runs in the browser instead of getting state through this code:
https://github.com/marko-js/marko/blob/7c5089b54c889cc8fc20c9f59eb0d591402e18b7/src/components/ComponentDef.js#L138-L153

### Possible Fix

<details><summary>Additional Info</summary>

### Steps to Reproduce

This bug is currently wrapped up in a complicated component, but I can try to create a reproducible example if needed.

</details>

**Comment by mlrawlings** [comment]
@yomed The code you reference there is the difference in how a split component and non-split component are mounted in the browser.  

Is your component a stateful component that has server-only initialization code?

If a component has server-only code, you can make sure the component only runs `onCreate` on the server by splitting it and ensuring that it is not placed under another stateful component that will re-render and trigger the full lifecycle at some point, but because it's split and a root component, the template would not be send down for re-rendering.

---

This change to call `onCreate`/`onInput` at mount time could potentially be reverted and we might want to revisit it.  We document that `onMount` is the [first lifecycle method called in the browser](https://markojs.com/docs/components/#codeonmountcode), but this hasn't been true since [`marko@4.3.0`](https://github.com/marko-js/marko/pull/672).  

Stateful components re-render as part of mounting.  For top-level components, they were using the values from `onCreate`/`onInput` then re-rendering, but components nested under these top-level component went through their full lifecycle (including `onCreate`/`onInput`).

Data generated server-side in `onCreate`/`onInput` is regenerated in the browser and this means a few things: 
- if data can only be generated on the server, it will break in the browser.
- non-serializable objects ([such as functions](https://github.com/marko-js/marko/blob/7c5089b54c889cc8fc20c9f59eb0d591402e18b7/test/components-browser/fixtures/widget-dom-events/component.js#L15-L17)) that get created in `onCreate` are re-generated client-side and work as expected
- data pulled from `out.global` needs to be [serialized](https://markojs.com/docs/server-side-rendering/#serializing-globals)

The above has been true for any components under a re-render root (top-level stateful component) since 4.3.  For consistency, #1010 made this the case for the root components as well.

/cc @DylanPiercey 

---

Apparently, we also have a way to [disable this behavior](https://github.com/marko-js/marko/pull/672):
> There is a chance that this might break existing apps. To revert back to the old behavior on a page-by-page basis you can do the following:
> 
> ```marko
> <marko no-browser-rerender />
> 
> <html>
>   ...
> </html>
> ```

**Comment by yomed** [comment]
Just for reference: In my particular case, I was using server-side cookies (to get correct server rendering), and then mapping all server-only code to noops on the client. I could theoretically change to using isomorphic cookie handling, and sending a little extra code to the client.
