### ISSUE TITLE
handlebars to markojs conversion

### ISSUE THREAD

**Issue by sido420** [marko-js/marko#1079]
Is there an easy way to compile/convert handlebar templates (.handlebars files) into markojs compatible files?

In my project, I have several handlebars files that I precompile into JS and include in my project to be  used by calling JS Handlebars.* method. What would be the fastest way to switch to marko for my use case?

**Comment by DylanPiercey** [comment]
Unfortunately there isn't a tool like this that I am aware of. You'd likely run into some hurdles because of the way the handlebars runtime works however it would technically be possible for some limited functionality to be converted to Marko. This would definitely be out of scope for this project however.
