### ISSUE TITLE
Library may interfere with Ublock origin

### ISSUE THREAD

**Issue by Galahan** [marko-js/marko#1102]
### Details

When I try to use Ebay with Ublock origin none of the functionality works properly. I filter the results in the sidebar, the sandtimer appears briefly, but the page is not updated. I then have to refresh the page to see the new results. This is the error I see in the web console in Firefox (sorry I don't know how to fill out the other details of this template):

21:30:33.224 this.$ is deprecated and Marko 4 will not have jQuery bindings.
OLD: this.$();
NEW: var $ = require("jquery"); $(this.el); 1 browse-page-desktop-pr-f619c6.js:92:75

Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead.  (unknown)
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://*.ebaystatic.com https://*.ebaystatic.com http://*.ebay.com https://*.ebay.com"). Source: var descGaugeInfo = {descST:(new Date())...

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 52.9.0 ESR:
- Operating System and version (desktop or mobile): Windows 10 (affects Windows 7 also)

### Steps to Reproduce

Install Ublock and use Ebay.co.uk, issue may not appear for some people. Issue occurs even with Ublock's power button set to off.
</details>

**Comment by DylanPiercey** [comment]
As far as I can tell this issue is not related to Marko. The deprecation warnings you mentioned should not change the behavior of the page regardless of a browser plugin.

Typically if a browser plugin is breaking the page there is not much we can or should do about that. However if you can narrow down exactly whats going on and if it is Marko related we can consider making a change here.

Closing this issue for now but feel free to provide any additional information if you believe this issue is related to Marko.
