### ISSUE TITLE
Unable to get components if using include

### ISSUE THREAD

**Issue by alexjalex** [marko-js/marko#1105]
In the code below, I have a page-player, which has needs to needs to access it's pages. But when using the <@content> syntax and <include(input.content)/>, the components inside of the <@content> are scoped to the very top of the app, not within the page-player.

```
<page-player key="main-page-player">
 <@content>
   <page key="introPage" pageId="intro">
     <@content>
      <div class="text-content text-center" key="text-content">
        <p>Introduction text</p>
        <btn-goto-page targetPage="next"><@content>Start</@content></btn-goto-page>
      </div>
     </@content>
   </page>
```

**Comment by mlrawlings** [comment]
This is behavior is correct.  A component can only access nodes that it owns, not necessarily all its children.  For term clarification: https://gist.github.com/mlrawlings/9b07279727cca359dd5f6f57671db24c

Normally, a component cannot "see" its transcluded content.  The `@` tags exist to allow passing content that isn't totally opaque to a component.   So you could do something like this instead:

```marko
<page-player key="main-page-player">
   <@page pageId="intro">
      ...
   </@page>
   <@page pageId="other page">
      ...
   </@page>
</page-player>
```

For repeated nested tags, you need to let marko know in a [`marko-tag.json`](https://github.com/marko-js-samples/ui-components-playground/blob/243a8779cfa0f76013ec2390abc8b14194307200/components/app-tabs/marko-tag.json) that these tags should come through as an array:
```json
{
  "@pages <page>[]": {
    "@pageId": "string"
  }
}
```

The UI Components playground has a [tab sample](https://github.com/marko-js-samples/ui-components-playground/tree/master/components/app-tabs) that is similar to what you'd need to do.

Also, if you only have a single content chunk you can just use the default one and `<include(input)/>` rather than creating an intermediate `<@content>` tag.
