### ISSUE TITLE
es6 template strings

### ISSUE THREAD

**Issue by sandro-pasquali** [marko-js/marko#111]
es6 template strings use the format ${expression}

I was wondering if marko can handle this (apparent) conflict? Sorry if I missed something in the docs.

**Comment by patrick-steele-idem** [comment]
Hi @sandro-pasquali, the Marko compiler processes `${expression}` found in JavaScript strings to produce compiled JavaScript code that uses concatenation to achieve the expected result. Essentially, you get the benefits of ES6 template strings inside Marko templates and there is no conflict with ES6 since the code is transpiled to ES5 compatible code at compile time.

For example, given the following template:

```xml
${"Hello ${data.name}"}
```

The compiled code will be similar to the following:

```javascript
"Hello "+data.name
```

Interestingly, if you want to use ES6 template strings you can still do that by using backticks instead of string quotes (Marko only process `${...}` tokens inside JavaScript strings). For example, given the following template:

```xml
${`Hello ${data.name}`}
```

The compiled output will be the following:

```javascript
`Hello ${data.name}`
```

The above compiled code will work exactly as expected in web browsers that support ES6.

Hopefully that answers your question, but let me know if not.

**Comment by sandro-pasquali** [comment]
Great. Thanks for the response!
