### ISSUE TITLE
Suggestion: Custom Jade tags

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#113]
I'm planning to leverage Jade to make it easier/faster to write the marko templates...

So far I've uncovered the following special marko and lasso tags:

```
<if
<include
<require
<var
<assign
<with
<else-if
<else>
<for
<def
<invoke
<layout-placeholder
<layout-use
<layout-put
<lasso-page
<lasso-head
<lasso-body
```

Am I missing any important pieces? Looks like [pencil](https://www.npmjs.com/package/pencil) would make it pretty easy to add such custom tags to Jade and then I can have a `gulp watch` task auto-compile to marko. Sweet :)

**Comment by patrick-steele-idem** [comment]
Hey @kristianmandrup, I'm just going through old issues to do some housecleaning. I'm going to go ahead and close this issue, but if this is still an issue/question please feel free to add more comments. 

On a related note, I plan on sharing a marko roadmap later this week. Work is [in-progress](https://github.com/marko-js/marko/tree/htmljs-parser) to integrate the new [htmljs-parser](https://github.com/philidem/htmljs-parser) as discussed in the following proposal: https://github.com/marko-js/marko/issues/90

The new syntax is much cleaner and more powerful. For example:

```xml
Hello ${data.name}!

<ul if(notEmpty(data.colors))>
    <li for(color in data.colors)>
        ${color}
    </li>
</ul>
<div else>
    No colors!
</div>

<if(notEmpty(data.colors))>
    <ul>
        <for(color in data.colors)>
            <li>
                ${color}
            </li>
        </for>
    </ul>
</if>
<else>
    <div>
        No colors!
    </div>
</else>
```

We will also be introducing a cleaner syntax for macros/functions:

```xml
<function renderTree(node)>
    Name: ${child.name}

    Children:
    <ul if(node.children)>
        <li for(child in node.children)>
            <renderTree(child)/>
        </li>
    </ul>
</function>

<renderTree(data.node)>
```

And ES6-style imports:

```xml
<module-imports>
    reverse from "./helpers";
    foo from "./foo";
</module-imports>

Hello ${reverse('Frank')}
```

Just wanted to share with you, because I think these changes will likely impact how you are doing things with the jade transpiler. If you have feedback, please share!

Thanks.
