### ISSUE TITLE
Problems using array with tags, '*' as first key!?

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#119]
I pass an array of the form:

```js
[
{label: 'my label', icon: 'users'},
{label: 'extra', icon: 'feed'},
]
```

`index.marko`

```html
<icon-list items="${data.items}"/>
```

`icon-list.marko`

```html
<for each="item in $data.items">
  $item.label
</for>
```

But when I debug, I get a strange '*': entry as my first key!? WTF!?

`list { '*': { items: [ [Object], [Object] ] } }`

Looks like it should be `data` in this case (`for each`) without the `$` sign. 
Not clear from the docs IMO.

```html
<for each="item in data.items">
  $item.label
</for>
```

Now we get an error about some strange error, 'unexpected token {'  Damn!

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup, if you have a marko-tag.json and you don't declare a certain attribute then it is considered a "splat" attribute and it is added to a special "*" property. The fix is to declare the `"@data": "expression"` attribute in your `marko-tag.json` file. See: https://github.com/marko-js/marko#defining-attributes

With that said, the Marko compiler should probably throw an error at time unless you explicitly add the "@*" attribute.  I'm going to investigate.

Also relevant: https://github.com/marko-js/marko/issues/90 (Proposal: Replace HTML parser with a new parser that recognizes attribute types)

**Comment by kristianmandrup** [comment]
Thanks, I figured that was the issue, since I had seen a brief mention somewhere about the `@*` being a "catch all" in your docs about the schema. But wasn't really clear that not declaring the schema value would cause this kind of problem. I guess when you go beyond strings, you currently have to specify the schema carefully in order to make marko understand. Kinda makes sense. I posted my solution/suggestion for proposal #90 which would make it awesome!!
