### ISSUE TITLE
marko migrate generates invalid code for arrow functions passed to attributes

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1268]
```
<CustomTag handler=((arg) => console.log(arg))/>
```
gets migrated to the following invalid code 

```
<CustomTag handler=(arg) => console.log(arg)/>
```

**Comment by DylanPiercey** [comment]
What version of marko-cli? I think this was fixed recently.

**Comment by cameronbraid** [comment]
6.0.3

**Comment by cameronbraid** [comment]
marko-cli  6.0.3
@marko/migrate 5.0.2

**Comment by cameronbraid** [comment]
it works fine with code like :

```
<CustomTag provider=((arg) => { return staticFunction() })/>
```

**Comment by DylanPiercey** [comment]
Is it possible to provide a larger snippet? Running the above snippet through the migrate appears to output properly for me (tested a few Marko versions also):

from:
```marko
<CustomTag handler=((arg) => console.log(arg))/>
```

to:
```marko
<CustomTag handler=(arg => console.log(arg))/>
```

**Comment by cameronbraid** [comment]
```
<SearchWidgetConfigEditor widgetConfig=tab vehicleCategoryItemsProvider=(()=>widgetConfig.vehicleCategoryItemsForTab(tab))/>
```

**Comment by DylanPiercey** [comment]
Thanks for the updated example, with this one I was able to reproduce the issue. FYI it is caused by bad paren matching in the printer and `(a) => b()` would work (becomes: `a => b()`), however `() => b()` would not work, and neither would `(a, b) => c()`.

Will release a patch later today https://github.com/marko-js/cli/pull/121
Thanks for flagging the issue 😄

**Comment by DylanPiercey** [comment]
Released a new version of Marko CLI with the fix.

**Comment by cameronbraid** [comment]
Good job .. thanks

Cameron
