### ISSUE TITLE
Line has extra indentation at the beginning

### ISSUE THREAD

**Issue by superbig** [marko-js/marko#1327]
### Details

When the first line in a marko template starts with a space, the following error is thrown.

{ Error: An error occurred while trying to compile template at path "...content.marko". Error(s) in template: 1) [src/pages/.../content.marko:1:1] Line has extra indentation at the beginning

### Expected Behavior

Spaces at start of first line are ignored and no error thrown.

**Comment by Sebring** [comment]
Sorry, why is this expected behavior?

I would not expect a template start with a space, especially not if using the concise syntax.

**Comment by DylanPiercey** [comment]
This is expected behavior due to supporting concise mode. That is why we have a special error message.

**Comment by Sebring** [comment]
Just to clarify my comment above, @DylanPiercey I was questioning the defined "Expected Behaviour" by the op in the post, not the actual expected behavior by Marko.

> superbig: 
Expected Behavior
Spaces at start of first line are ignored and no error thrown.

> Sebring: 
Sorry, why is this expected behavior?
I would not expect a template start with a space, especially not if using the concise syntax.
