### ISSUE TITLE
SystemJS/jspm ES6 loader support/plugin

### ISSUE THREAD

**Issue by cyparu** [marko-js/marko#134]
With the coming standard ES6 loader support currently implemented in [SystemJS](https://github.com/systemjs/systemjs) & [jspm](http://jspm.io/) having a MarkoJS plugin would be great! Using the [SystemJS Handlebars](https://github.com/davis/plugin-hbs) plugin as a starter might be a good idea: 

**PS:** Since AMD support was [dropped](http://psteeleidem.com/announcing-marko/#switched-to-commonjs-modules-for-compiled-templates) by switching to CommonJS, I'm just wondering what's the currently recommended (non-Browserify!) recipe for using MarkoJS with AMD/RequireJS (including bundling/compiling) :question:

**Comment by patrick-steele-idem** [comment]
Since there is currently no JavaScript engine that natively supports ES6 modules, why not just use babel to transpile the ES6 module code into [mostly] equivalent ES5 code (that uses CommonJS module syntax)? Once you have ES5 code you can build browser JavaScript bundles using almost any of the popular JavaScript module bundlers (or the JavaScript module bundler can do the transpiling). That seems like a better strategy than buying into a custom module loading system such as SystemJS or jspm (each with their own quirks and proprietary features). When I look at SystemJS and jspm I am reminded of RequireJS and all of the ugly configuration that it required. If SystemJS or jspm do not support the [browser field spec](https://gist.github.com/defunctzombie/4339901) for remapping a server-side JavaScript module to a different browser-side JavaScript module then that would be a problem for marko. I recommend using [Lasso.js](https://github.com/lasso-js/lasso) or [Browserify](http://browserify.org/) (or possibly [Webpack](http://webpack.github.io/)) as your JavaScript module bundler for building client-side bundles of your JavaScript code.

I would not recommend trying to make marko (or any other module written in the Node.js way) work with RequireJS. Have you considered transforming your AMD code into CommonJS so that you can drop AMD and RequireJS completely (both are dying technologies).

With that said, if someone in the community wants to build a custom Marko loader for SystemJS or jspm then I'll try to help out, but it is not something I am interested in coding.

**Comment by philidem** [comment]
I investigated integrating Babel a while ago and found that it was very
easy although I was waiting on some changes from Babel to make it more
efficient. Specifically, the Babel transpiler builds the Abstract Syntax
Tree (AST) of the code and we were hoping to leverage their AST instead of
also parsing it with esprima. I think Babel has since made some changes to
make it easier and better for tools like Lasso (bundler) to utilize ES6 via
Babel.

**Comment by cyparu** [comment]
10x for your detailed answers. So ... no easy AMD/RequireJS MarkoJS integration here :worried: 
Anyhow, I'm currently looking into the maturing SystemJS/jspm since aside of supporting any module format (AMD, CommonJS, global, ES6, System/register) and native-transpilers (TypeScript, Babel, Traceur) it is future-proof being the (single AFAIK) reference implementation/polyfill of the ES6 module loader. 
If time permits I'll look into creating a **plugin-marko** plugin & bundler for MarkoJS integration.

**Comment by wheresrhys** [comment]
I've been mulling over which cool new thing to ditch from my project: jspm or marko. 

Marko wins :+1:

**Comment by patrick-steele-idem** [comment]
Glad to hear @wheresrhys, thanks for sharing! I know you are using webpack, but I recommend checking out Lasso.js... I think it is pretty awesome and it offers a lot of features that webpack doesn't offer :)

**Comment by mlrawlings** [comment]
We will not be supporting SystemJS or AMD moving forward, but we do need to figure out some things regarding ES Modules.  See #850
