### ISSUE TITLE
Should benchmark with Svelte

### ISSUE THREAD

**Issue by scorsi** [marko-js/marko#1350]
Hello,
I just discovered Marko and I was surprised to don't find Svelte in your benchmarks, is it much more faster than Marko ? 😛 
Btw, great job, it looks awesome ! 👌

**Comment by Sebring** [comment]
Have a look at [krauset/js-framework](https://github.com/krausest/js-framework-benchmark) and the [official result page](https://krausest.github.io/js-framework-benchmark/2021/table_chrome_88.0.4324.96.html).

There are (at the time writing) no benchmarks of Marko 5 however. Needless to say you can filter out Svelte and Marko to get a better overview.

**Comment by ryansolid** [comment]
That's only clientside rendering performance which is only part of the story.

If you are going to compare Marko to Svelte it has to be server-side since that is generally where you'd be using Marko. https://github.com/marko-js/isomorphic-ui-benchmarks

That being said Svelte is missing here. I did add Svelte 3 for an article I was writing but haven't setup a PR. Here is my fork (https://github.com/ryansolid/isomorphic-ui-benchmarks/tree/article). My findings were:

https://miro.medium.com/max/875/1*lk2cUAlYUCSxNOL1kZpxpA.png
https://miro.medium.com/max/875/1*P_K2ma2widqlMH4iTYTlRw.png

As you can see Marko is much faster than any of the other libraries here.
