### ISSUE TITLE
Breaking change in minor version: body-only-if

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#1357]
Changing `body-only-if` to the dynamic tag resulted in attributes still evaluating and following code that used to work before 4.18 is not working anymore:

```marko
<a body-only-if(!router) href=router.url('buka')>Some text</a>
```

**Comment by mlrawlings** [comment]
@tinovyatkin thanks for reporting this!

Besides reverting the change, I see two paths forward.

#### Option 1: Make it so that the dynamic tag lazily evaluates its attributes:

```marko
<${router ? "a" : null} href=router.url('buka')/>
```

The compiled output put the attributes in a function that will only be called if the tag needs to be rendered
```diff
marko_dynamicTag(
  router ? "a" : null, 
- { href: router.url("buka") }, 
+ () => ({ href: router.url("buka") }), 
  null, out, __component, "0");
```

#### Option 2: Migrate `body-only-if` to a safer output

```marko
$ var attrs = () => ({ href: router.url('buka') ]);
<${router ? "a" : null} ...attrs />
```
