### ISSUE TITLE
False deprecation warning on namespaced non-marko components…

### ISSUE THREAD

**Issue by hedefalk** [marko-js/marko#1367]
### Details

I use some facebook markup that I let facebook parse from DOM:

```
      <fb:login-button 
        auto-logout-link="false"
        button-type="continue_with" 
        size="large"
        scope="public_profile,email" 
        use-continue-as="true">
      </fb:login-button>
```
In my onMount I then let the facebook API do it's thing with that and it works fine:

```FB.XFBML.parse(component.getEl(…)```

### Expected Behavior
No warnings 
### Actual Behavior

I get deprecation warnings for nested syntax:

```
MIGRATION
The "<my-tag:nested>" tagName syntax is deprecated. Please use the "<@nested>" tagName syntax instead. See: https://github.com/marko-js/marko/wiki/Deprecation:-legacy-nested-tag
  at src/web/marko/components/fb-login-modal.marko:11:6
```

I guess this is a corner case when I stick non-marko custom components in there, but maybe it would be possible to suppress these warnings for non-marko components. dunno…?

**Comment by mlrawlings** [comment]
Thanks for reporting!

Yes, this migration should be modified so that it only does this if there is a parent tag that matches the part before `:`.

For example, this would still go through the migration path:
```marko
<fb>
    <fb:login-button 
        auto-logout-link="false"
        button-type="continue_with" 
        size="large"
        scope="public_profile,email" 
        use-continue-as="true">
    </fb:login-button>
</fb>
```

But `<fb:login-button>` alone would not.

**Comment by mlrawlings** [comment]
If anyone is interested in getting their feet wet contributing to Marko, this would be a good first issue to tackle.  

**Implementation**
The relevant code is here:
https://github.com/marko-js/marko/blob/master/src/core-tags/migrate/all-tags/legacy-nested-tag.js#L9-L11

This `if` should add a check so that is also returns early if there is no ancestor that matches the nested tag prefix (`fb` in this example).

You can walk the ancestors by asking for the current `el`'s `parentNode`.
https://github.com/marko-js/marko/blob/master/src/compiler/ast/Node.js#L307-L309

**Testing**
It can be tested by adding a top-level tag that shouldn't be migrated here:
https://github.com/marko-js/marko/blob/master/test/migrate/fixtures/legacy-nested-tag/template.marko
And updating the expected snapshot to assert that is is in fact not migrated:
https://github.com/marko-js/marko/blob/master/test/migrate/fixtures/legacy-nested-tag/snapshot-expected.marko

**Comment by tigt** [comment]
I’m interested in tackling this, as I had the same problem when using Marko to generate an [OpenSearch description file](https://developer.mozilla.org/en-US/docs/Web/OpenSearch).

(Also making a note here so I remember: this would also close #1297)

**Comment by DylanPiercey** [comment]
The current recommendation is to either:

* Use a `marko.json` to mark these tags as `"html": true` https://markojs.com/docs/marko-json/#options
* Use the dynamic tag which will always become a native tag when a string is passed, eg `<${"fb:login-button"}>`
