### ISSUE TITLE
Move component.json definitions into components

### ISSUE THREAD

**Issue by sandro-pasquali** [marko-js/marko#1406]
I'm wondering how close we are to this:

> Note: Future versions of Marko will work toward describing these definitions/types within the component itself, largely reducing the need for this configuration file.

While the file based model is actually useful at the tooling layer, for me keeping it in sync with the current component defs is somewhat tedious (and error raising), and having this file lying around, for me, isn't ideal.

Thanks for a great system.

**Comment by tigt** [comment]
From talking to the devs about this in the Gitter chat, the future is probably TypeScript integration.

**Comment by DylanPiercey** [comment]
Since this is more of a question than an issue I'm going to close it.

To answer the question though, it is a little way out still. We've made significant progress to adding TypeScript support with the Marko 5 release, however, the tooling around that will take some time. Our focus is getting out Marko 6 and either in tandem with that or shortly after TypeScript support will become a priority.
