### ISSUE TITLE
Create a migration tool for switching to the new Marko with the htmljs parser.

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#146]
For context, please see [Proposal: Replace HTML parser with a new parser that recognizes attribute types](https://github.com/marko-js/marko/issues/90)

All of the details are not finalized for the new parser and template syntax, but we wanted to go ahead and create this issue to start the discussion and see if there was interest from folks in the open source community taking ownership of this task. Happy to answer any questions :)

**Comment by yomed** [comment]
How do you envision this? I assume it would automatically
1) transform if/else/for syntax in all files
2) transform syntax for all custom tags
2) remove attribute references in marko-taglib.json files
4) delete marko-tag.json files

Anything else?

**Comment by philidem** [comment]
So the main thing that we need to do is fix how attributes are delimited. If the marko tag definition says that an attribute is a string or if the attribute is not defined in the tag then surround the tag with double quotes. For expressions, numbers, boolean, and non-string types simply then surround then remove the quotes and surround the value with parentheses. For example, transform `some-number="123"` to `some-number=123`.

The new for-loop and if/else/else-if syntax should be used in place of the standard attributes. For example, `<div for="x in y">` should become something like `<div for(x in y)>`.

We can keep the marko-tag.json files for reference but they wouldn't be used anymore to infer attribute types (since type will always be an expression now). Also note that marko-tag.json files would still need to be used for describing tag transformers.

The migration tool should probably leverage `htmljs-parser` to parse the old templates since it will be able to properly parse the new and old syntax. This would be helpful in case the migration tool is ran multiple times for the same templates.

This isn't a comprehensive guide but I think these are the key things that would need to be migrated.
