### ISSUE TITLE
Set up Prettier to auto-format/fix PRs

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#1465]
> [Real question: why does the CI run check-format and not just format?](https://github.com/marko-js/marko/pull/1431/commits/cee250a5ab1a5e411b5f8c45961a898e46e72664) - @tigt

We have prettier set up to check the format of files in the CI and it fails if there is a mismatch.  This isn't a big deal for our normal workflow since the pre-commit hook runs prettier, but the hooks don't run in every environment - particularly with web commits which are very convenient for doc changes.

Ideally, this isn't something we'd have to think about and the formatting would be automatically fixed.

I [experimented a bit ago](https://github.com/marko-js/marko/commits/test-format-web) with a [GitHub bot](https://github.com/kevgo/prettifier) that did this, but there were some issues - the main one being the bot used its own version of prettier which meant it didn't necessarily format exactly the same way the project's version of prettier formatted.

Some options and potential resources:

- Committing back from Travis 
  - https://gist.github.com/willprice/e07efd73fb7f13f917ea
- Using a GitHub Action
  - https://github.com/bltavares/actions/tree/master/prettier
  - https://github.com/cds-snc/github-actions/tree/master/auto-commit

**Comment by basickarl** [comment]
Hello!
Regarding the question "why does the CI run check instead of fix", I had this question in my team last week and it's very simple. Code _committed_ should all be in the same format as the rest of the code, this will make code review easier, since it will be in the same format. 

Regarding why I'm posting here now. Making a parser plugin that prettier can include would be a way of dealing with this? https://prettier.io/docs/en/options.html#parser

Wouldn't this basically just use the javascript and html plugin and make sure that prettier recognizes the .marko suffix? As you can see, the vue and angular parsers do this.
