### ISSUE TITLE
require.extensions deprecated

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#151]
https://nodejs.org/api/globals.html#globals_require_extensions

Given that this method is deprecated, we might want to look into requiring .marko files differently. Maybe by handling compilation separately and then `require('template.marko.js')` instead?

**Comment by patrick-steele-idem** [comment]
Yes, require extensions are deprecated, but I'm not too concerned. As stated in the docs:

> Since the Module system is locked, this feature will probably never go away.

I disagree with their decision to deprecate the feature, but I do think there are better ways to extend the module loading system to add support for new compile-to-JavaScript languages such as JSX and marko. Worst comes to worst, we provide a script to precompile all templates to JS and use `require('template.marko.js')` instead, but that would impact developer usability since it would introduce an unnecessary build step that we don't have now. 

How we have implemented the Node.js require extension for marko avoids the problem of having a global. The global require extension that gets installed by marko simply delegates the compilation to JS to the appropriate marko compiler based on where the source template is on disk. There is no harm with registering the require extension multiple times and in different packages.

On a related note, I would like to see a tool that can be used to precompile all templates and that replaces all `require('./template.marko')` calls with `require('./template.marko.js')`. This would be useful as a `prepublish` script for publishing shared packages that make use of Marko templates.

**Comment by patrick-steele-idem** [comment]
That's true that `require.extensions` was deprecated, but I am not too concerned. According to the docs:

> Since the Module system is locked, this feature will probably never go away. 

I disagree with their decision to deprecate that feature without providing a suitable alternative. There's definitely a need for compile to JS languages such as Marko and JSX. Forcing a precompile makes things more difficult and more complicated since it introduces an unnecessary build step that is not needed now. Worst comes to worst, we could precompile all templates and require the `.marko.js` files directly....

The Node.js require extension for marko avoids most of the problems with globals since the require extension just delegates the template compilation to the appropriate version of marko based on where the template is located on disk. There is no harm in installing the marko require extension multiple times and it can be multiple versions of marko in a single app.

On a related note, I do think there would be a benefit to offer a tool for Marko that could be used as a `prepublish` script to replace all `require('./template.marko')` calls with `require('./template.marko.js')` and to have it precompile all templates in the process.

**Comment by patrick-steele-idem** [comment]
Hey @yomed, I'm just going through old issues to do some housecleaning. I'm going to go ahead and close this issue, but if this is still an issue/question please feel free to add more comments. 

As a separate issue I think we should explore the option of precompiling all templates and updating the JS code as a prepublish step. Please feel free to open an additional Github issue if you have specific thoughts on how to avoid using `require.extensions`. Thanks.
