### ISSUE TITLE
How to use images in marko template?

### ISSUE THREAD

**Issue by hetang** [marko-js/marko#152]
I want to use custom images in marko templates. But not able to find any documentation related this.

**Comment by viviangledhill** [comment]
Use just regular html tags 

```<img src="http://i.imgur.com/L7TM5P1.jpg">```

**Comment by patrick-steele-idem** [comment]
That's true @viviangledhill.

However, if you want the image to go through the Lasso.js asset pipeline then you should use the `<lasso-img>` tag:

```xml
<lasso-img src="./foo.jpg"/>
```

This might produce the following HTML output depending on how Lasso.js is configured:

```html
<img src="/static/foo-25b047cc.jpg" width="100" height="100">
```

The referenced image will also be moved into the appropriate output location. If there are any plugins to minify images then those plugins will process the image as well.

Here are the docs that were just added: https://github.com/lasso-js/lasso#%3Classo-img

**Comment by viviangledhill** [comment]
That's great and totally makes sense for local images.

On a side note for lasso-image - Would be also great if it would deliver webp images if the browser supports it. Conversion might be too expensive ... just an idea.

**Comment by patrick-steele-idem** [comment]
@viviangledhill automatic conversion to webp is a good suggestion. Assuming the webp image is cached I don't see it being too expensive. The tricky part is that we would have to have a good mechanism for making Lasso.js aware of the target browser's user agent so that it can optimize accordingly. Maybe open a separate Github issue for that feature request to Lasso.js?

I'm going to go ahead and close this issue, but let us know if you run into any other issues related to images and Lasso.js. Thanks.
