### ISSUE TITLE
onMount not firing

### ISSUE THREAD

**Issue by retrohacker** [marko-js/marko#1569]
### Details

`index.marko`

```
class {
  onCreate() {
    console.log("create")
  }
  onRender() {
    console.log("render")
  }
  onInput() {
    console.log("input")
  }
  onUpdate() {
    console.log("update")
  }
  onMount() {
    console.log("mount")
  }
}

<html>
  <body>
    <h1>hai</h1>
  </body>
</html>

```

When I run `marko-starter server` I see `create`, `input`, and `render` on the server, but in the browser console I don't see `mount`. Is this expected?

**Comment by DylanPiercey** [comment]
@retrohacker we're planning on phasing out `marko-starter`. We've got a new set of tools to get up and running with a Marko app. If you are just getting started it might be best to give it a try instead.

You can use [@marko/create](https://github.com/marko-js/cli/blob/master/packages/create/README.md) to set up an app from one of our examples (defaults to a simple starter project). To get up and running just run `npx @marko/create --template basic`.

The default starter project uses [`@marko/serve`](https://github.com/marko-js/cli/tree/master/packages/serve) and [`@marko/build`](https://github.com/marko-js/cli/tree/master/packages/build) which use webpack instead of lasso and drastically simplify the setup process for Marko.

We are also happy to help you solve this issue with `marko-starter`. If you are able to share an example repository with the reproduction in it that would be helpful!
