### ISSUE TITLE
A marko's stream rewrites hallo-world.marko

### ISSUE THREAD

**Issue by Globik** [marko-js/marko#159]
Excuse me, I'm newbie to marko. I'v tried the hello-world example on koa.js with a stream via pipe proccess.stdout. So first time in template all was OK written as must to be. Via console terminal all was also fine, it's work but when I opened the file next morning I'v seen that marko engin rewrite the file of  his own way with helper's javascript functions, but my  Hallo ${data.name}!   is gone, simple disapeared. What I'v wrong made? Or all that features must be by default?

```javascript
var fs=require('fs')
var  duf=''
require('marko/node-require').install();
//two ways at once
//first way:
var template=require('./views/hello-world.marko');
template.render({name:"Bob",colors:["yellow","red","brown"]},function(err,output){
	if(err) console.log('error :',err);
	console.log('output :',output)
})
//2th way:
var das=template.stream({name:"bobika"});
das.on('end',function(){console.log('\nDAS END DAS END!!! ON END!!\n')})
das.once('end',()=>console.log('\nDAS Once END ONCE END!!!\n'))
das.on('finish',()=>console.log('\r\nDAS ON FINISH!!!\n'))
das.on('error',(e)=> console.log('\n DAS ERROR!!!! :',e))
das.on('data',(c)=> console.log('DATA!!! :',c.toString()))
das.on('readable',()=> {var buf;while((buf=das.read())!==null){
	duf+=buf;console.log("\nBUF :",duf)}})
var sis=process.stdin;
var sisout=process.stdout;
process.stdout.on('error',process.exit);
process.stdout.on('exit',function(){console.log('ended')})
sis.pipe(das).pipe(sisout);
```
*****************************************************
and here my hallo-world.marko in the morning:

```javascript
function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne,
      escapeXml = __helpers.x,
      forEach = __helpers.f,
      escapeXmlAttr = __helpers.xa;

  return function render(data, out) {
    out.w(' hello ' +
      escapeXml(data.name) +
      '! ');

    if (notEmpty(data.colors)) {
      out.w('<ul>');

      forEach(data.colors, function(color) {
        out.w('<li style="color: ' +
          escapeXmlAttr(color) +
          '">' +
          escapeXml(color) +
          '</li>');
      });

      out.w('</ul>');
    }
    else {
      out.w('<div>no colors!</div>');
    }

    out.w(escapeXml(data.bazar) +
      '<b>simka: </b>' +
      str(data.simka));
  };
}
(module.exports = require("marko").c(__filename)).c(create);
```

**Comment by Globik** [comment]
In the file hierarchie must be two files? One for hello-world. marko and one compiled  hello-world.js???
is that by default? Hmm. One must be restart server to keep changes in the template file. So bad and slowly for a site developing.

**Comment by Globik** [comment]
In a hello-world example for colors /li produces extra empty li pairs. Why? When you delete last /li, so ok. Is a bug?

**Comment by Globik** [comment]
Only opening tags are modified for conditionals and looping???

**Comment by patrick-steele-idem** [comment]
Hi @Globik, let's start with your first question:

 > I opened the file next morning I'v seen that marko engin rewrite the file of his own way with helper's javascript functions, but my Hallo ${data.name}! is gone, simple disapeared.

When a Marko compiles a template such as `template.marko` it will generate a new file next to the original file named `template.marko.js`. The original source file is definitely not deleted. If it is gone it is because you accidentally deleted it but most likely you are just not noticing it. The generated JavaScript file is what gets loaded by Node.js (or sent to the browser).

------

And for your second question:

> The server must be restart to keep changes in the template file every time. So bad and slowly for a site developing. Is it true?

Depends on how you are watching files. Make sure you add `*.marko.js` to your ignore patterns (e.g. `.gitignore`). Since the `*.marko.js` files are generated at runtime you will want to make sure those files are ignored.

------

And for your final question:

> Only opening tags are modified for conditionals and looping???

When you make an element conditional using the `if` attribute or if you make it repeated using the `for` attribute then both the starting and ending tag will be wrapped. Hopefully it is clear from the `Try Online` example: http://markojs.com/try-online/#Simple_Hello_World

------

Let us know if you have any other questions.

**Comment by patrick-steele-idem** [comment]
Hey @Globik, I'm just going through issues to do some housecleaning. I'm going to go ahead and close this issue, but if this is still an issue/question please feel free to add more comments. Thanks.
