### ISSUE TITLE
Nested property of undefined

### ISSUE THREAD

**Issue by redben** [marko-js/marko#162]
Given this template

```html
<p>Author ${data.author.name}</p>
```
this data:
```js
template.render({});
```

I get this error
```
      escapeXml(data.author.name) +
                           ^
TypeError: Cannot read property 'name' of undefined
```

Is this normal behavior ? Does marko handle properties on undefined paths or am I missing something ?

**Comment by patrick-steele-idem** [comment]
Hey @redben, that is the expected behavior. Anything inside `${ ... }` is just JavaScript and it will be evaluated just like any other JavaScript code (if you take a look at the compiled code this should be clear).

Because Marko templates compile down to CommonJS modules you can import the `lodash/object/get` function to provide safe access to nested properties as shown below:

```xml
<require module="lodash/object/get" var="get"/>
<p>Author ${get(data, 'author.name')}</p>
``` 

You'll need to install `lodash` into your project for the above code to work:

```bash
npm install lodash --save
```

If you don't want to use a third-party module, you can also do the following:

```xml
<p>Author ${data.author && data.author.name}</p>
```

Does that work for you? Hope that clarifies.

**Comment by redben** [comment]
thanks @patrick-steele-idem that's what I did (lodash).

On the other hand, wouldn't it be interesting to have that handled by marko ? It seems most template engines have such a feature.

**Comment by patrick-steele-idem** [comment]
Hey @redben, it's true that many templating engines interpret expressions and handle safely reading nested properties. However, doing that by default results in worse runtime performance and it limits the power of the templating language since expressions cannot be arbitrary JavaScript code. Marko has always tried to be be as close to pure JavaScript wherever possible. This keeps the runtime tiny, improves performance and it allows templates to be more powerful.

In theory, we could offer the `get` as a builtin helper to avoid having to import it. Something worth considering (especially if it is only imported if it is used in the template). Thoughts?

**Comment by redben** [comment]
I see what you mean.

As for offering  `get` as builtin helper, one can use lodash as you suggested. May be it's good to keep the library as slim as possible by not providing extra features, until there's sufficient demand for it by the community?

**Comment by patrick-steele-idem** [comment]
Hey @redben, what's nice about marko is that it only requires in things that are required. That way when you use a JavaScript module bundler to send a compiled template to the browser there is no extra baggage. As long as we made it so that the `get` function was only `require`'d if used then I see no harm as offering that as a feature. The hard part is figuring out if `get` is required because currently aren't fully parsing the JavaScript expressions used in a template (using something like esprima or acorn), but that is something we are considering for the next release of marko. Probably low priority though since there is a fairly clean workaround. Thanks for your feedback.
