### ISSUE TITLE
Express JS Plugin

### ISSUE THREAD

**Issue by adammcarth** [marko-js/marko#165]
Hey team.

Are there any plans on the roadmap for an Express JS rendering plugin for Marko? Currently we render templates with...

```javascript
require("marko/node-require").install();
var app = require("express")();
var template = require("./hello.marko");

app.get("/hello", function(req, res) {
    template.render({
        name: "Adam",
        fruits: ["Apples", "Oranges", "Grapes"]
    }, res);
});
```

But what about a plugin that leverages Express's built-in render helper?:

```javascript
var app = require("express")();

var Marko = require("marko-express"); // example lib name
app.engine("marko", Marko({ fabulous: "options" }));
app.set("view engine", "marko");

app.get("/hello", function(req, res) {
    res.render("hello", {
        name: "Adam",
        fruits: ["Apples", "Oranges", "Grapes"]
    });
});
```

Is something like this on the cards, or did you avoid it because of performance reasons/Marko best practices or something? I guess one of the advantages of initializing Marko as an express app engine (like above) is that  you can pass options to Marko, such as `writeToDisk`, in a far nicer way than currently available. It also means we can set a base directory to reference `.marko` templates relative from, and not need to have an extra line to load the template into a variable before rendering content.

**Comment by patrick-steele-idem** [comment]
Hey @adammcarth, thanks for the question. That is something we have thought about, but we decided _not_ to build an Express view engine for various reasons:

The Express view rendering engine only supports callback-style view rendering that is not compatible with streaming. As a result, the Express view rendering engine has worse performance and less flexibility. On top of that, the Express view rendering engine includes its own view resolving code (instead of just using the Node.js module resolving code) and it requires global/app-level configuration to make everything work. Finally, the Express view rendering engine introduces a new way to render a template that only works on the server and only with Express. The Express view rendering engine, while simple, is far more complicated than just rendering a template directly to an HTTP response stream. The only drawback to not using the Express view rendering engine is that if your templates or view rendering code needs information associated with the incoming request then you must manually add that data to the template data (possibly using [$global](http://markojs.com/docs/marko/language-guide/#global-properties)). I guess another possible "drawback" is that you need to require in the template in the view controller code, but I see that as a good thing since it promotes modularity.

I wrote a blog post on this topic that you should check out as well: [Bypassing Express View Rendering for Speed and Modularity](https://strongloop.com/strongblog/bypassing-express-view-rendering-for-speed-and-modularity/)

Hope that answers your question! Let us know if you have any other questions. Thanks again.

**Comment by adammcarth** [comment]
Thanks for the response @patrick-steele-idem. That blog post you wrote pretty much cleared everything up for me - seems like using the built-in express renderer can indeed be quite harmful in some cases.

I'm interested in making my apps more modular. I like the structure you use for basic apps...

- pages/
  - home/
    - index.js
    - style.css
    - template.marko
  - login/
    - index.js
    - style.css
    - template.marko

...but I'm wondering how that idea gets applied, to, say - a blog post? Would you opt for something like?:

- pages/
  - posts/
  - post_show/
  - post_edit/
  - post_update/

Just trying to get the Marko concepts down-pat. Thanks for all your help :)

**Comment by patrick-steele-idem** [comment]
Hey @adammcarth, glad you found that article helpful. Pretty much every product team at eBay building webapps on the Node.js stack have adopted the modular directory structure and the feedback has been very positive. I also see a similar trend with other frameworks and libraries.

For a blog post, I think that directory structure looks good. A page typically has a top-level route associated with and it will typically have a unique page controller and page template. For the [markojs.com blog](http://markojs.com/blog/), there are a set of pages associated with the blog that you can take a look at: https://github.com/marko-js/markojs.com/tree/master/src/pages/blog

Those pages each have a corresponding route. I prefer to put all of the routes in a single place so that anyone looking at the application source code can quickly figure out which routes map to which pages.

The layout taglib is used to separate out page layout from page content in cases where you have multiple pages that share a common layout. For example: https://github.com/marko-js/markojs.com/tree/master/src/layouts/default

I hope that helps.

**Comment by adammcarth** [comment]
Cheers mate, wonderful.
