### ISSUE TITLE
How should we define configuration options for Marko?

### ISSUE THREAD

**Issue by adammcarth** [marko-js/marko#166]
Hey all.

So at the present, Marko doesn't have a uniform way of defining configuration options when first initializing the library in your project. For example, setting the `writeToDisk` option (which prevents templates from compiling to the file system) is achieved with:

```javascript
// Current configuration method
require("marko/compiler").defaultOptions.writeToDisk = false; // what if more config options arise?
require("marko/node-require").install();
```

It works for now, but it's not ideal - particularly with the future in mind where configuration could play a bigger role with Marko. Here are some alternatives for defining configuration that have been suggested so far...

#### 01. Configuration File

This solution is probably the most promising on this list. Essentially, the idea is that you can create a file in the base directory of your project that Marko will read and pull configuration options from. A potential name for the file might be `.markoc` (a hidden file, standing for 'marko config')...

```javascript
{
    "writeToDisk": false,
    ...
}
```

One debate that does arise from this is whether your *Marko Tag Lib* should also be defined here with the compiler configuration, or if it should still be kept in a seperate `marko-taglib.json`. My personal opinion is that all Marko configuration should be defined from a central place to make life easier, but the argument for keeping the `marko-taglib.json` seperate from compiler configuration is that it's less complex. My question to that response is, how often do we intend to add/update component directories? If it's very infrequently (as I suspect), then I just don't see why it needs its own file. Just my $0.02 on the matter though. Please share your own thoughts.

#### 02. Pass Configuration Block To Installer

An idea I had was to potentially pass in a configuration object when Marko is required...

```javascript
// Example
require("marko/node-require").install({
    writeToDisk: false,
    ...
});
```

It's certainly a more traditional solution, but this approach is not ideal given the way the Marko runtime is loaded by Node.js so this one is not recommended.

#### 03. ???

If you've got any ideas or suggestions for alternative ways that configuration could be defined for Marko, please share it with us below. I think it's important that we have this discussion now so that more default configuration options can be introduced by the community down the track. If we can agree on a standard now, we can start exploring other potential config for Marko. Please share any thoughts you have :)

**Comment by philidem** [comment]
I like the idea of using **01. Configuration File**. As a slight variation, I would recommand `.marko` (not `.markoc`) because I don't it's necessary to distinguish between Marko runtime and compile-time options.

I know that @patrick-steele-idem is hard at work on Marko v3 so maybe we could target this feature for that version?

**Comment by philidem** [comment]
And, regarding having a separate `marko-taglib.json`, I'm actually liking your idea of converging on a single file. This would also make the compiler a little simpler since it wouldn't have to look for two files when looking for configuration.

The only downside with using something like `.marko` is that files that start with "." are ignored by default in Unix-like operating systems. Maybe `marko.config`, `marko.config.json` or `marko.json` instead?

**Comment by adammcarth** [comment]
I agree with @philidem. I think a centralised configuration file in the project root for all default Marko settings, and the name `marko.json` gets my vote so far.

Do you want to elaborate more on why you would want to keep the Marko Taglib seperate @patrick-steele-idem?

**Comment by patrick-steele-idem** [comment]
Thank you for sharing your detailed thoughts, @adammcarth and @philidem! 

:+1: on `marko.json`. After giving it some more thought I'm also in favor of using `marko.json` to both register custom tags and provide compiler configuration.

I'm also in favor of requiring that this file be placed in the root directory of the package. Currently we allow `marko-taglib.json` to be placed in any directory and the compiler just searches up from the template file. This works, but it introduces the overhead of searching the file system and it also results in marko searching outside the main project's directory which is not good.

I also agree that we should wait until the next major version of `marko` to make this change since it is a breaking change, and we have wanted to revisit taglib loading anyway. I'll add this to the roadmap (which still needs to be written up and formally shared).

If you have any other thoughts or suggestions please share. Thanks again!

**Comment by jsumners** [comment]
I would prefer being able to pass a configuration object into some sort of `require('marko').config()` method. I don't like the idea of messing with Node's `require` function, so I don't use `marko/node-require`. I use `marko.load()` for loading templates.

I normally write my applications to look for an application specific configuration file, or have one fed to it. The application then uses the properties of that configuration file to initialize any modules it uses that could potentially need some configuring. I don't really want to edit multiple configuration files for one application.

**Comment by patrick-steele-idem** [comment]
Supporting `require('marko').configure({})` is not bad, but the problem is that if the command line compiler is used to compile a template then it won't be configured the same way. Ideally, configuration would all be loaded declaratively from files. The only problem is if configuration needs to be environment specific.

> I don't like the idea of messing with Node's require function, so I don't use marko/node-require. I use marko.load() for loading templates.

Longer term, I would like to see an npm `prepublish` step that modifies all code as such:

_Before:_

```javascript
var template = require('./template.marko');
```

_After:_

```javascript
var template = require('./template.marko.js');
```

With that approach, you still get the convenience of requiring a template, but you don't have to worry about installing the require extension for production usage and third party packages wouldn't depend on the Node.js require extension for Marko. The Node.js require extension for Marko is only there for convenience because it allows for less code to load a template:

```javascript
var template = require('./template.marko');
var template = require('marko').load(require.resolve('./template.marko.js'));
```

In this case, I think it is better to be pragmatic instead of worrying about violating some Node.js tenet. The fact is, Marko is really just a transpiler that takes your Marko template file and converts it into a CommonJS module that Node.js can load and that is compatible with any JavaScript module bundler. The Node.js require extension for marko is just doing the transpiling on first require. Babel provides a Node.js require extension for ES6 transpiling.

**Comment by jsumners** [comment]
My statement about the require patching was in response to idea 2 in the original post. It proposes passing the configuration in during the install of the require patch. I was merely pointing out that not everyone uses that aspect of Marko. I understand that it is a convenience method, and that Marko is really just compiling the HTML based language into JS. It doesn't matter to me if Babel or other things also patch the require method -- I don't use any of them.

**Comment by mlrawlings** [comment]
Global configuration is now supported by:

```js
require('marko/compiler').configure({ writeToDisk: false, preserveWhitespace:true });
```
