### ISSUE TITLE
URL path and query parameters

### ISSUE THREAD

**Issue by treeder** [marko-js/marko#1714]
I must be missing something, but I can't seem to find how to get URL and query parameters. 

For example, if I have a URL like `/stuff/123?id=456

How do I set that up so that it would use the `stuff` page and then how could I get the path parameter and the query parameter? Or does that require using a server integration?

**Comment by tigt** [comment]
Correct, whatever you’re using for HTTP listeners in Node.js would provide these. The specifics vary by framework so the list could be infinite, but here are the 3 most common:

<dl>
<dt>Koa
<dd>Just <a href="https://koajs.com/#context"><code>ctx.query</code></a> out of the box. For <code>POST</code> requests, you’ll need something like <a href="https://www.npmjs.com/package/koa-bodyparser"><code>koa-bodyparser</code> to provide a <code>ctx.req.body</code> object</a></a>.

<dt>Express
<dd><a href="http://expressjs.com/en/4x/api.html#req"><code>req.query</code> and <code>req.body</code></a>.

<dt>Vanilla Node.js
<dd>Only provides <a href="https://nodejs.org/api/url.html#url_class_urlsearchparams">the <code>URLSearchParams</code> builtin querystring parser</a>, which means default Node can only handle <code>GET</code> requests and <code>POST</code> with <code>application/x-www-form-urlencoded</code> — you’ll need an npm module for <code>multipart/form-data</code>.
</dl>

(Vanilla Node is only as common as it is because [`@marko/serve`](https://github.com/marko-js/cli/tree/main/packages/serve) and [`@marko/build`](https://github.com/marko-js/cli/tree/main/packages/build) only use the builtin `http` module.)

However, for each case you’ll need to put the `query`/`body` objects from the parsed requests into Marko templates yourself — [the server integrations](https://markojs.com/docs/server-integrations-overview/) do not in fact do that for you. I personally use Koa kinda like this:

```js
import Koa from 'koa'
import markoTemplate from "./whatever.marko"

const app = new Koa()
app.use(ctx => {
  ctx.type = 'text/html;charset=utf-8'
  ctx.body = markoTemplate.stream({
    $global: {
      query: ctx.query,
      posted: ctx.req.body
    }
  })
})
```

```marko
<section>
  <h2><code>GET</code> parameters</h2>
  <pre>${JSON.stringify(out.global.query, null, 2)}</pre>
</section>

<section>
  <h2><code>POST</code> parameters</h2>
  <pre>${JSON.stringify(out.global.posted, null, 2)}</pre>
</section>
```

**Comment by treeder** [comment]
Ok, thanks for the info, I'll give it a try. It would be nice to support this kind of thing out of the box. Maybe like sveltekit does it: https://kit.svelte.dev/docs#routing-advanced-rest-parameters

**Comment by ryansolid** [comment]
I think it is important to distinguish the difference between the core framework from the prebuilt template. Ie.. the difference between Svelte vs SvelteKit.

@tigt's answer is the general one. In a similar way if you were to use Svelte directly there would be no specific solution for routing as it does not come built-in in Svelte.

However, It's worth mentioning if you are using [Marko CLI](https://github.com/marko-js/cli), the templates that use Marko Build/Serve, with its built-in file-based routing, that you can get the path params on `input.params.___` and the queryString is available at `input.query`. Here's an example of them both being used in a simple CLI based app: https://github.com/ryansolid/marko-hackernews

**Comment by treeder** [comment]
@ryansolid had a quick glance through that project, I think that's what I'm looking for. Once I have a chance to try it out, I'll report back.

**Comment by treeder** [comment]
Thanks for the help! @ryansolid that's exactly what I was looking for. Found those docs here: https://github.com/marko-js/cli/blob/main/packages/serve/README.md#route-params for anyone else looking. It doesn't have an example with the `/x/:y` style though. Might want to link to your hackernews clone repo from there. 

BTW, can't get over how fast all of this stuff is, both compiling and rendering 🤯

**Comment by treeder** [comment]
@tigt how do you get around this, I copied your code exactly:

```
Unknown file extension ".marko" for /home/treeder/dev/treeder/tokentapper-marko/index.marko
```

**Comment by tigt** [comment]
I personally use [the `@marko/rollup` plugin](https://github.com/marko-js/rollup) to build my application, which handles that part for me. If you’re doing it in raw Node, Marko has a way to teach `require()` about the `.marko` extension, but the docs don’t mention it anymore and [its source code mentions it’s going to be deprecated](https://github.com/marko-js/marko/blob/main/packages/marko/node-require.js).

**Comment by treeder** [comment]
I'm struggling to get anything working, seems like the docs are out of date or something for server integrations at least. I'm on Node 16, maybe that has something to do with it. The only thing that has worked for me is the Marko CLI, it's the only thing that's worked out of the box. 

If the CLI way of doing things could run some code to preload data before rendering, then add it to inputs, I think I'd have everything I need.

**Comment by tigt** [comment]
The Marko CLI _should_ add `input.query` and `input.params`… are you accessing them at the topmost `.marko` file? If it’s a child component, you may have to pass those `input`s down to it.

**Comment by treeder** [comment]
@tigt yes, that part works. Preloading is a different issue (which I think I tried to do in a .marko file but had issues with awaiting on data,.I think it's this #675).

**Comment by treeder** [comment]
I went back to the code to recall what the issue was and made a new issue here: https://github.com/marko-js/marko/issues/1722

**Comment by treeder** [comment]
Any reason `input.query` is string and `input.params` is a map?

This is what I"m getting:

```
PARAMS: { id: 'ABC' }
QUERY: amount=1
```

**Comment by DylanPiercey** [comment]
@treeder params are handled explicitly by the router and so it makes sense to provided the (already parsed) result to the user. With params there are various formats people use in the wild, especially around nesting.

Luckily it seems node is moving toward the web standard way of parsing the querystring which will work nicely here also.

Basically you can do:

```marko
$ const query = new URLSearchParams(input.query);
$ const amount = query.get("amount");
```

(see https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)
