### ISSUE TITLE
Using JS operators as attribute names can cause attributes to be parsed incorrectly

### ISSUE THREAD

**Issue by Khauri** [marko-js/marko#1748]
### Details

Using `in` (and potentially other operators, but I haven't tried them all) as an attribute causes some inputs to get joined together when parsed. For example:

```marko
 <css-transition timeout=5000 classes="fade-up" appear in>
```

Results in an input object of:

```json
{
    "timeout": 5000,
    "classes": "fade-up",
    "appear in": true
}
```

### Expected Behavior

`in`, and potentially other operators, should be marked as reserved and throw an error when used as an attribute name.

### Actual Behavior

`in` causes the the attributes to be parsed incorrectly, joining them together in the final input.

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Desktop 94.0.4606.81
- Operating System and version (desktop or mobile): macOS Big Sur
- Link to your project:

### Steps to Reproduce

1. Create a component and pass `in` as an attribute along with some others.
2. Observe the input parses incorrectly.

**Comment by DylanPiercey** [comment]
@Khauri there we're recently parser changes that improve things here. NOW these keyword operators only apply when the keyword is not followed by a `=/,;:>`. This means it's safe to use these keywords as regular value attributes.

If you wan't to use them as a boolean attribute there are some cases where it is still ambiguous, however the code you've shared in this issue would no longer be ambiguous.

I think this is probably as good as we can do here since we don't want to currently restrict using these keywords as attributes since `in` is used as an attribute in the `<for>` tag.
