### ISSUE TITLE
Marko Component Library

### ISSUE THREAD

**Issue by jtsui** [marko-js/marko#1758]
I'm interested in using marko to build components for a component library, with options to build a commonJS or umd module for other apps to `import` and render via `renderToString`.

Looking at the webpack and rollup plugin integrations, it seems like both primarily support building webapp vs a library of components. 

Is this correct? Are there any sample build configurations where marko is built into a library?

**Comment by DylanPiercey** [comment]
@jtsui we recommend publishing Marko components in their source form since it allows us to continue to optimize the output code of the template, auto migrate it when features are deprecated, and more. A Marko component compiled with one version of the Marko compiler is not guaranteed to work in a runtime for a different version of the compiler (even across patch releases).
