### ISSUE TITLE
Support async DOM when JS is disabled

### ISSUE THREAD

**Issue by L1lith** [marko-js/marko#1809]
### Description

I was thinking about progressive enhancement and HTML first, and it would be so cool if Marko could utilize iframes as a fallback to allow asynchronously modifying content in browsers with JS disabled. How would this work?

1. The browser puts an iframe around the content it would like to load asynchronously (this splitting that part of the DOM into a separate request)
2. Marko streams data to that iframe as it arrives (kind of like HTTP long-polling) without blocking up the rest of the page
3. Optionally, Marko could do things like send `<meta http-equiv="refresh" content="1">` in order to remove items from inside the iframe

We can put these iframes inside of `<noscript>` tags to only enable it as a fallback behavior

### Why

- This would allow Marko to load things out of order on the first render
- This would provide a HTML fallback mechanism for page updates

### Possible Implementation & Open Questions

How would Marko maintain the state and handle routing etc?
Possibly this is something that might be better as an external lib?

### Is this something you're interested in working on?

I'm interested in helping but I'm not familiar with Marko's source code

**Comment by DylanPiercey** [comment]
Hi @L1lith thanks for the suggestion! I think in practice this would end up having quite a bit worse perf since you couldn't send that html initially with the page request. It'd also add a lot of complexity since it'd require the server being aware of state for each of these sections. Besides that there's the inherent issues of iframes around layout / encapsulation that would make it difficult to work as a fallback for our out of order streaming.

I think in general a JS based out of order streaming is ideal and the time I think it makes sense to worry about disabling this feature is when crawlers are requesting the page, but it's simple enough to special case things for those.

**Comment by tigt** [comment]
I agree with the decision not to pursue this, but @L1lith I’d like to emphasize I am a big fan of the motivations behind it: wanting more robust fallbacks, creativity using the platform in interesting ways, and alternate solutions to the same problem with an eye on performance.

Something like this was once possible in initial page requests via `multipart/x-mixed-replace`. Unfortunately, browsers have stopped supporting that MIME type in the top-level browsing context… I was disappointed, since I also would have loved out-of-order streaming without JS. When I was playing around with it, though, there were problems I hadn’t anticipated. I _think_ your proposal would share some, so I’ll list them in case they’re dealbreakers for you too:

- If the user changes the DOM state (form inputs, toggling a `<details>`, selecting text, etc.) before the page re-updates (with the next `part` in mine, with the `http-equiv="refresh"` in yours), their changes are lost. It’s _ludicrously_ hard to do anything about this.

- The stop/refresh/back buttons start behaving weirdly, especially when `<iframe>`s are involved.

- JS execution becomes slower and harder to bugfix. For `multipart` because of re-executions, for `<iframe>`s because of the additional browsing contexts’ JS state, which is famously a perf villain on mobile.

**Comment by niutech** [comment]
I've proposed a no-JS solution for HTML streaming in #2185.
