### ISSUE TITLE
Use of deprecated mutation events in development mode

### ISSUE THREAD

**Issue by dario-piotrowicz** [marko-js/marko#1857]
### Details

When working on a Marko application in development mode, I saw both in chrome (v.105) and firefox (v.105) present warnings about the use of mutation events (firefox presents the warning just once whilst chrome presents if after every dom manipulation):

![Screenshot at 2022-10-02 18-18-31](https://user-images.githubusercontent.com/61631103/193467569-7ad92683-e502-40ef-b8c2-0bbb4c7aee9a.png)

![Screenshot at 2022-10-02 18-25-49](https://user-images.githubusercontent.com/61631103/193467597-4f729b68-b306-4356-875b-21e0d5c7cc40.png)

I am pretty sure this is caused by the following code:
https://github.com/marko-js/marko/blob/955ea006b89ee303d25f415d88962cd3b6f020f8/packages/marko/src/runtime/components/util/index-browser.js#L162-L167

Mutations events are indeed deprecated and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent) also mentions that its use is not recommended. So an equivalent implementation using [mutation observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) should be applied instead. 

<details><summary>Additional Info</summary>

### Environment

- Browsers: Chrome 105 and Firefox 105
- Operating System: Ubuntu 20.04.2 LTS

### Steps to Reproduce

- Create a new Marko app via: `npx @marko/create`
- Tweak the console verbosity if needed
- See the warning/s appear in the console as soon as the app bootstraps 

</details>

**Comment by dario-piotrowicz** [comment]
I put this as a bug, but I am not sure if it could be considered that or maybe a feature request?

Anyways, I am not too familiar of how Marko works but this on face value seems like a simple change to make, please let me know if you'd like me to have a crack at it :slightly_smiling_face:

Unless this needs to be implemented using Mutation Events for some specific reason?

**Comment by DylanPiercey** [comment]
@dario-piotrowicz this is something I'd like to see changed however there isn't a modern browser API that lets us achieve what we want. Essentially what we're trying to do is capture a stack trace of when comment marker DOM nodes (used internally by Marko) are removed from the DOM so that if that section is re-rendered we can point to where things went wrong. MutationObserver doesn't get fired early enough that we can capture the stack trace here.

One potential thing we could do is disable this in dev mode by default and print a generic error if you've done this and provide some opt in way to allow you to use these older API's to get more information about the error.

**Comment by DylanPiercey** [comment]
Seems chrome no longer warns with this error so closing for now.
