### ISSUE TITLE
Improve get started guide

### ISSUE THREAD

**Issue by tonytopper** [marko-js/marko#196]
It seems like http://markojs.com/docs/marko/get-started needs some improvement.

Angular 2's use of file name labels on their code samples is helpful here: https://angular.io/docs/ts/latest/quickstart.html  You see this a lot throughout the community.   It's a nice way to help people get their head around the setup process quickly so they can get down to learning the syntax and API and also building something.

**Comment by mlrawlings** [comment]
It definitely needs some improvement.  It needs to be more of a tutorial rather than a list of features that a beginner might find useful.

I like the idea of filename labels.  I think we could create a nice widget (using Marko of course) that could take a directory path and create the widget from that.  Maybe it could be generated from a gist so that users on reading on github would still be able to view code snippets.  Maybe that's not worth it and they should just read it on markojs.com.

**Comment by mlrawlings** [comment]
The docs have been revamped for Marko 4 (and we now have filename labels with code snippets! 😄 ).  If there are any specific issues, a new issue can be opened.
