### ISSUE TITLE
Deprecation warnings in Chrome

### ISSUE THREAD

**Issue by xtremespb** [marko-js/marko#2023]
### Details

I'm getting a deprecation warning in Chrome version 115.0.5790.170 (Official Build) (arm64) which is related to the Marko code.

### Expected Behavior

No deprecation warnings.

### Actual Behavior

```
[Deprecation] Listener added for a synchronous 'DOMNodeRemoved' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
```

Error is here:

```javascript
if ("MARKO_DEBUG") {
  var warnNodeRemoved = function (event) {
    var fragment = event.target.fragment;
    if (fragment) {
      var baseError = new Error(
        "Fragment boundary marker removed.  This will cause an error when the fragment is updated."
      );
      fragment.___markersRemovedError = function (message) {
        var error = new Error(message + " Boundary markers missing.");

        baseError.stack = baseError.stack.replace(/.*warnNodeRemoved.*\n/, "");

        // eslint-disable-next-line no-console
        console.warn(baseError);
        return error;
      };
    }
  };
  exports.___startDOMManipulationWarning = function (host) {
    host.addEventListener("DOMNodeRemoved", warnNodeRemoved);
  };
  exports.___stopDOMManipulationWarning = function (host) {
    host.removeEventListener("DOMNodeRemoved", warnNodeRemoved);
  };
}
```
I didn't enable the MARKO_DEBUG variable.

### Possible Fix

Check the code?

<details><summary>Additional Info</summary>

### Your Environment

Debian Linux 12 or Mac OS Ventura 13.04
32 GB RAM
Node v20.5.1 and v19.4.0

### Steps to Reproduce

Go to [Heretic Demo](https://demo.hereticjs.org) and open up the browser console

**Comment by xtremespb** [comment]
The problem is that I'm running the code built in production mode, built by Webpack.
On some [project pages](https://demo.hereticjs.org/signIn?r=/boilerplate) the deprecation warnings are showing in interval.

Is there are a way to disable this behaviour in production mode?

**Comment by xtremespb** [comment]
@DylanPiercey I've explicitly set MARKO_DEBUG environment variable to false, now it's gone. Setting of  NODE_ENV to "production" didn't work. 

My suggestion is to set MARKO_DEBUG to "false" as a default value, so for me this seems to be a bug ;-)

**Comment by DylanPiercey** [comment]
The debug mode changes a bunch of things, including better error messages, reduced minification and things like this to detect bugs.

Changing the default here doesn't really solve the problem, but we should maybe make it more easy to tell when you're running in a specific mode and also ensure things line up with the build instead of just NODE_ENV at the time of build.

My guess here is that there is something in your webpack config which is causing it not to set NODE_ENV to a const of production. This will cause various tools to pull in debug and unoptimized stuff which isn't great. Can you verify you're webpack config properly sets that?
