### ISSUE TITLE
Transformed tag not triggering code-generation (v3)

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#217]
It is my understanding that should be able to change the tagName of an element at the transform stage and have it trigger a code-generator/renderer at the generate stage, but this does not appear to be the case.  Am I doing something wrong? Is this expected behavior? A bug?

NOTE: This is on the lastest version of the `htmljs-parser` branch.

# Setup
*index.js*
```javascript
require('marko/node-require').install();
require('./test.marko').stream().pipe(process.stdout);
```

*marko-tabglib.json*
```json
{
	"<new>": {
		"code-generator":"./test-generator"
	},
	"<*>": {
		"transformer":"./test-transformer"
	}
}
```

*test-transformer.js*
```javascript
module.exports = function transform(el, context) {
	console.log('CALLED TRANSFORM')
	if(el.tagName !== 'new') {
		if(el.getAttributeValue('transform')) {
			el.setTagName('new')
		}
	}
}
```

*test-generator.js*
```javascript
module.exports = function codeGenerator(el, codegen) {
    console.log('CALLED GENERATOR')
    el.removeAttribute('new')
    return el
};
```

# Test 1, unexpected

Rendering the following template:

*test.marko*
```html
<div transform=true />
```

I get the **output**:
```
CALLED TRANSFORM
<new transform></new>
```

But I'm **expecting**:
```
CALLED TRANSFORM
CALLED GENERATOR
<new></new>
```

# Test 2, working as expected

If I change the template to use the `<new>` tag initally I do get the expected output:

*test.marko*
```html
<new transform=true />
```

**output**:
```
CALLED TRANSFORM
CALLED GENERATOR
<new></new>
```
The node still goes through the transform function, but it is not touched.  I'm guessing this is the difference.

**Comment by patrick-steele-idem** [comment]
Nice to see that you are digging into the code for the Marko v3 compiler :)

I understand why you are expecting a different output, but the reason you are seeing the behavior that you are seeing is that at parse time we build all of the nodes in the AST based on the tag definitions and we associate the code generator when the node is initially created. Therefore, when the Marko parser encounters the `<div>` node it is creating an `HtmlElement` node and the `HtmlElement.prototype.generateHtmlCode` method is being used as the code generator for the node. Changing the tag name does _not_ change the code generator and I think it is best to keep that way. However, you can create a new replacement node in your transformer (instead of modifying the existing node):

```javascript
module.exports = function transform(el, context) {
    console.log('CALLED TRANSFORM')
    
    if (el.getAttributeValue('transform')) {
        var newTagName = 'new';
        var newAttributes = {
            foo: context.builder.literal('bar')
        };
        
        var newEl = context.createNodeForEl(newTagName, newAttributes);
        el.replaceWith(newEl); // Remove the old HtmlElement out of the tree and replace it with the new one
    }
}
```

NOTE: I just added the `replaceWith(newNode)` method as a convenience method (see https://github.com/marko-js/marko/commit/2ce5493c9afaa1389f943946bc7e4d19ddf134b1) You will need to pull the latest code if you want to test the above code.

Hope that makes sense. Please let us know if you have any other questions/thoughts/concerns. Thanks!

I'm going to go ahead and close this issue, but feel free to respond here.

**Comment by mlrawlings** [comment]
Makes sense.  Thanks for clarifying, and the `replaceWith` method is much appreciated!
