### ISSUE TITLE
marko-compiler-options adds blank newline in the output

### ISSUE THREAD

**Issue by felixsanz** [marko-js/marko#240]
`<marko-compiler-options>` shouldn't add a newline to rendered output because it's an option to the compiler, not part of the template at all. So it shouldn't cause any side-effect in the output.

I was about to submit a PR with a fix, but @patrick-steele-idem said in gitter:

> The marko compiler allows certain nodes/tags to be marked as "noOutput" so that they get ignored when applying whitespace removal rules. We probably just need to set that flag for the <marko-compiler-options> tag. We should add a test case to verify.

So that's a better solution. I was also trying to provide a PR for this, but i have no idea about how to do it.

I was about to add `el.noOutput = true;` below line 138 in [Parser.js](https://github.com/marko-js/marko/blob/master/compiler/Parser.js#L138), but i think the PR shouldn't/wouldn't be accepted like that.

**Comment by philidem** [comment]
@felixsanz I think you should proceed with the solution that I recommended because `<marko-compiler-options>` is treated very special inside `Parser.js` and never gets added to the AST so I don't think @patrick-steele-idem's suggestion would help here. I would recommend setting some type of _flag_ to `true` to indicate that the next newline character should be discarded. The flag should be reset back to `false` after you processed the next block of character data (so that you don't inadvertently remove the wrong newline character).
