### ISSUE TITLE
Start a awesome-marko github repo

### ISSUE THREAD

**Issue by regiellis** [marko-js/marko#255]
I feel there is not enough awareness out in the community about Markojs, nor is there a curated list of examples, articles, and good libraries from around the net. May there should be one ...

**Comment by alim4** [comment]
I agree with this. It would be really cool to see how eBay leverages Marko for their main site

**Comment by patrick-steele-idem** [comment]
I agree with you both that this is needed. I will create a repo with a few links as a starting point and add more links as I find them and hopefully others can help make it better as well.

I'm also going to push our product teams at eBay to work on some blog posts that share how we are using Marko and Marko Widgets at eBay. It will take a little longer, but I also want to gather some numbers on how many UI components our teams have created (there's a lot) so that people will better idea how heavily Marko is being used at eBay. Teams have also done some interesting things with Lasso.js as well to create webapps that have specialized content for various devices. I'll definitely keep this issue open and hopefully will have something to show very soon.

Thanks!

**Comment by regiellis** [comment]
Since I suggested this, I really should join in the fun; I will be submitting libs, components, etc as I make them over the next couple of weeks. I will do my best to get some articles out about Markjs on my Medium blog.

**Comment by patrick-steele-idem** [comment]
That would be really awesome @regiellis. I feel like if we just can get a few people blogging, then that would help a ton with awareness. If you want, I would be happy to review any early drafts :)

**Comment by mufumbo** [comment]
love it, will commit something when you define a format

**Comment by sebastianmacias** [comment]
+1 I have been looking for UI kits such as vuematerial.github.io, vuetifyjs.com for marko but haven't found any so far. An awesome-marko repo would be very helpful to group all available resources under one page

**Comment by patrick-steele-idem** [comment]
For future reference: https://github.com/wujjpp/isomorphic-marko

**Comment by tigt** [comment]
Some more examples:

* [GOV.UK Elements in Marko](https://github.com/gunjam/govuk-elements-marko) 
* [jesse1983/Marko router5](https://jesse1983.github.io/marko-router5/)
* [jesse1983/redux-simple-event](https://github.com/jesse1983/redux-simple-event)
* [Kendo design](https://kenlo.design/components) uses Marko for its components
* [marko-amp](https://www.npmjs.com/package/marko-amp): Accelerated Mobile Pages taglib for MarkoJS
* [Storybook for Marko](https://www.npmjs.com/package/@storybook/marko): …a UI development environment for your Marko components. With it, you can visualize different states of your UI components and develop them interactively.

**Comment by SandeepVattapparambil** [comment]
https://github.com/SandeepVattapparambil/learnMarko
LearnMarko is a sample web application built using Express + MarkoJS + MaterializeCSS at the front end and consuming Unsplash API for the data. This project is intended for educational purpose only.
