### ISSUE TITLE
Question - Regarding to the usage of macro

### ISSUE THREAD

**Issue by hung-phan** [marko-js/marko#270]
Hi, I have a question regarding to the usage of macro for marko@v3. I defined the following macros in `helpers.marko` and want to use it in another file. For example,

helpers.marko
```
<macro csrf-meta-tags(csrf)>
    <meta content=csrf name="csrf-token">
</macro>

<macro javascriptIncludeTag(src)>
    <script type="text/javascript" src=src></script>
</macro>
```

I want to use it in `application.marko`. How can I do this? I tried the include but it didn't work for me

**Comment by hung-phan** [comment]
Just found out this http://markojs.com/docs/marko/custom-taglibs/

**Comment by hung-phan** [comment]
Sorry, to reopened this again. I have some questions regarding to the usage of macro in multiple files. What is the benefit of using macro over custom-taglibs? Also for template inheritance like layout-taglib, how can I the layout can understand the data from current template?

For example,

index.marko
```
<layout-use("./layout.marko")>
    <layout-put into="title">My Page</layout-put>
    <layout-put into="body">BODY CONTENT</layout-put>
</layout-use>
```

layout.marko
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><layout-placeholder name="title"/></title>
</head>
<body>
    <p>
        <layout-placeholder name="body"/>
        <custom-tag env=data.env />
    </p>
</body>
</html>
```

**Comment by hung-phan** [comment]
If I run `marko.load('index.marko').stream({ env: 'production' })`, the layout.marko will not understand data.env right?

**Comment by patrick-steele-idem** [comment]
Hey @hung-phan, sorry I wasn't able to respond earlier.

A macro is just inline include/partial that can only be used within the current template.

An include is a partial that is separated to a separate file so that it can be used by custom templates.

A custom tag is a more powerful version of an include that allows some JavaScript code to act as the "rendering controller" for the custom tag. In addition, a custom tag can be mapped directly to a template. Custom tags also have the benefit that they are easier to use since they get registered with a tag name.

A layout is just a reusable template that has placeholders

Here's some guidance on deciding when to use what:

- Use a macro if you need to create repeat some HTML within the same template
- Use an include if you need to break up a template into multiple templates and all of the files are closely related and in the same directory.
- Custom tags are almost always a better option than includes since they are the most flexible and offer better encapsulation of rendering logic. 
- Use a layout template when you have multiple pages or components that share a common layout/structure

> Also for template inheritance like layout-taglib, how can I the layout can understand the data from current template?

You an pass data to a layout template as the second argument to the `<layout-use>` tag (see http://markojs.com/docs/marko/layout-taglib/#layout-data):

```xml
<layout-use("./layout.marko", { foo: 'bar' })>
    <layout-put into="title">My Page</layout-put>
    <layout-put into="body">BODY CONTENT</layout-put>
</layout-use>
```

The data object passed in as the second argument will be available in the layout template as part of the `data` object (e.g. `data.foo`).

> If I run `marko.load('index.marko').stream({ env: 'production' })`, the `layout.marko` will not understand `data.env` right?

You should use sparingly, but you can pass "global" data that is available to all templates. See: http://markojs.com/docs/marko/language-guide/#global-properties

Therefore, you can do the following:

```javascript
marko.load('index.marko').stream({
    $global: {
        env: 'production'    
    }
})
```

Global data is available in all templates (even templates for custom tags) or wherever you have access to the `out`. For example: 

```xml
<span>The current environment is ${out.global.env}</span>
```

Hopefully that answers your questions, but please let me know if you need more clarification. I'm going to go ahead and close the issue, but please feel free to reopen or add more comments here and I will take a look.

**Comment by hung-phan** [comment]
It did resolve my problem. Thanks @patrick-steele-idem.

**Comment by hustcer** [comment]
Would it be better if `helpers.marko` could be included in other files ? `custom-taglibs` is a little complicate for the beginners.

**Comment by patrick-steele-idem** [comment]
@hustcer creating a custom tag is as simple as creating a `template.marko` file. 

For example:

`src/components/app-my-helper/template.marko`

```xml
<div>
  Hello ${data.name}!This is my awesome helper.
</div>
```

That's all that is required to create a custom tag. No other files are required.

The custom tag can then be used in any directory at or below the `src/` directory. For example:

`src/pages/home/template.marko`:

```xml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hello</title>
    </head>
    <body>
        <app-my-helper name="Frank"/>
    </body>
</html>
```

For more details: http://markojs.com/docs/marko/custom-taglibs/#scanning-for-tags

**Comment by hustcer** [comment]
Cool, this is more easy to understand than the doc. Thanks a lot.
