### ISSUE TITLE
Safari is waiting first await tag

### ISSUE THREAD

**Issue by Eldar-X** [marko-js/marko#361]
Safari is waiting the completion of the first await tag

When i try to render async fragment (await tag)

**In Chrome without client-reorder**
1. Outer html rendered
2. First await tags rendered
3. Second await tag rendered
_With client-order same except order of await tags like expected._

**In Safari without client-reorder**
1. Not render outer html until all await tags done
2. All html rendered together

**In Safari with client-reorder**
1. Safari is waiting until first await tag done
2. Outer html and first await tag rendered
3. Second await tag rendered

**Comment by patrick-steele-idem** [comment]
Hi @Eldar-X, what version of Safari are you using and which OS? When I test Safari version 9.1.2 (11601.7.7) on OSX everything is working as expected using the following sample app: https://github.com/marko-js-samples/marko-progressive-rendering

It will vary by browsers, but most browsers must receive a minimum threshold of bytes before the initial render. It's possible that for your app you are not sending down enough HTML for the initial HTML and this is causing the browser to just buffer the received HTML instead of rendering the initial page. If you can provide more details on your setup or a sample app I will investigate some more.

**Comment by Eldar-X** [comment]
Hi @patrick-steele-idem my safari version is 9.1.2 (11601.7.7) on OSX El Capitan and same issue on https://github.com/llambda/koa-boiler.

**Comment by Eldar-X** [comment]
I found solution! it was happen because i run server under browser-sync proxy.
