### ISSUE TITLE
Marko Not Sending 304

### ISSUE THREAD

**Issue by RyenNelsen** [marko-js/marko#368]
### Context

When Marko renders a template using `marko/express`, and there are no differences, it still sends the page over with a 200 HTTP status code.
### Expected Behavior

If no differences are detected, `marko/express` should send a 304 to avoid extra data being sent.
### Actual Behavior

Currently, no matter what, `marko/express` will send the template over with a 200 HTTP code.
### Possible Fix

Store an in memory hash of the previous render and check if it matches the current render; if they match send a 304 concluding nothing has changed.

<details><summary>

Additional Info</summary>

### Your Environment
- Version used: 3.9.4
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 52, node 6.3.1
- Operating System and version (desktop or mobile): Mac OS X 10.11.6
### Steps to Reproduce
1. Install Marko within an Express project.
2. Require `marko/express`
3. Use `res.marko` to compile a template and send it to a client
4. Look at the response status headers and see that Express is responding with a 200 HTTP code

</details>

**Comment by patrick-steele-idem** [comment]
Hey Ryen, I don't think this is an issue with the Marko middleware since there is no way for Marko to know that the response is going to be the same before rendering. I think the responsibility of setting the cache headers and setting HTTP status codes should reside in your application logic. If you have any more thoughts please share.

**Comment by RyenNelsen** [comment]
That is what I thought, but if I use pug (jade), templates will render, and if not changes are detected, express will emit a 304. With Marko, it will always send a 200, and force the client to download the entire page.

**Comment by patrick-steele-idem** [comment]
In order for `res.marko()` to send a 304 it would need to buffer the response in order to calculate an etag based on the final HTML output and then use that etag to determine if 304 should be sent based on incoming request and it would also need to set the etag header for the response. That is certainly something we could offer as a feature, but it would need to be opt-in since buffering would prevent streaming/progressive HTML rendering (a huge reason to use Marko). In a perfect world, your page controller would calculate the etag independent of template rendering (this would would have the advantage that there would be no CPU cycles and memory wasted rendering a template that didn't need to be rendered).

I'm not opposed to offering feature as an enhancement, but it would need to be opt-in. If it something you are interested in working on, here is the related code:

- https://github.com/marko-js/marko/blob/master/express.js
- https://github.com/jshttp/fresh
- https://github.com/jshttp/etag

Please let me know if you are interested in working on this.

**Comment by patrick-steele-idem** [comment]
And just to add. something like the following might be nice:

```javascript
res.marko(template, templateData, { etag: 'weak' });
```

**Comment by RyenNelsen** [comment]
Although you would have to store a lot of data in memory if you wanted the page controller to calculate it without a rendered template to cross check it with. One way or another the data needs to be verified, and I do agree with not wanting to waste CPU cycles if data hasn't changed.

Does anyone have any ideas that would be efficient? I'm thinking of generating hashes from the data here, but that seems like a waste of CPU cycles itself.

**Comment by patrick-steele-idem** [comment]
Did you go any farther with this @RyenNelsen? Generating a hash of the data would work if the output is completely based on the backend data, but it would definitely require some extra CPU cycles. Depending on how your backend data is structured, you could store a "version"/"revision"/"last modified" or some other value with the data to track changes to the data and use that value to also set the `etag` and check freshness. That would all be outside the scope of marko. The only thing that marko could do is buffer up the output HTML in order to calculate an etag and compare freshness to conditionally send down a `304 not modified`

**Comment by RyenNelsen** [comment]
Sadly I have not had any time to work on this feature as of yet.

**Comment by mlrawlings** [comment]
This is not a concern of Marko core.  It would be possible create a `marko-express-etag` package that used `template.renderToString` and a caching strategy to implement this.
