### ISSUE TITLE
Maximum call stack exceeded?

### ISSUE THREAD

**Issue by yamikuronue** [marko-js/marko#378]
## Bug Report

I'm getting "maximum call stack exceeded". What am I doing wrong?

### Context
I'm trying to benchmark marko against our current favorite, handlebars, because I expect it'll be a lot faster. I'm running a matcha test, so I have the following code:

```
const handlebars = require('handlebars');
require('marko/node-require').install();
const fs = require('fs');

const data = // [snipped for brevity]

suite('Post template', () => {
//snipped Handlebars test 

	bench('marko', (next) => {
		const template = require('./post.marko');
		template.render(data, () => {
			//throw away the render output
			next();
		});
	}); 
```

### Expected Behavior
I should see benchmark results

### Actual Behavior
During the marko test, an error is thrown that aborts the suite

<details><summary>Additional Info</summary>

### Your Environment
I'm using C9, running this using matcha for node.js

### Stack Trace
```
RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at Object.posix.resolve (path.js:442:52)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:316:31)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/ubuntu/workspace/benchmarks/matcha-tests.js:35:20
    at iterate (/home/ubuntu/workspace/node_modules/matcha/lib/matcha/bench.js:178:5)
    at /home/ubuntu/workspace/node_modules/matcha/lib/matcha/bench.js:180:7
```

</details>

**Comment by patrick-steele-idem** [comment]
For performance reasons, if a render completes synchronously then the callback is invoked synchronously. Therefore, if you repeat the rendering when the callback is invoked then you will eventually get a `Maximum call stack exceeded` error because the stack trace keeps growing.

The simple solution is to break up the stack trace using `setImmediate()`:

```javascript
bench('marko', (next) => {
    const template = require('./post.marko');
    template.render(data, () => {
        //throw away the render output
        setImmediate(next);
    });
});
```

If you add `setImmediate` for `marko` then make sure you also add it for `handlebars` so that the results are not skewed.

On a related note, have you taken a look at the following benchmarks that include `marko` and `handlebars`?: https://github.com/marko-js/templating-benchmarks

It's very easy add add a new comparison group with your own templates. If you want to improve those benchmarks with more comparisons I would encourage you to send a PR.

If you have any other questions or issues please let me know.

**Comment by yamikuronue** [comment]
Thanks, that worked great! Yeah, I got the idea from your benchmark set, but my group wanted to see how it performs with our templates. I figured it was simple enough to do.. until I hit this issue >.>

Thanks again!
