### ISSUE TITLE
Question: How do I debug stream/async rendering errors?

### ISSUE THREAD

**Issue by aaronshaf** [marko-js/marko#380]
Hello, marko neighbors! I use Express with Marko. Example:

```
template.render(data, res)
```

How do I handle rendering errors in this case? Thanks!

**Comment by patrick-steele-idem** [comment]
There are no `try...catch` blocks in marko so exceptions will not be caught by marko (this includes render-time exceptions due to programming errors in marko templates). 

Certain errors (such as timeouts associated with the `<await>` tag) will be emitted on the target stream. You can listen for those errors by adding a listener for the `error` event:

```javascript
res.on('error', function(err) { ... });
```

If you use promises then promises will have an implicit `try...catch` block. If the promise passed to an `<await>` tag gets rejected then the `<await-error>` tag can be used to show alternate content: [`<await-error>`](http://markojs.com/docs/marko/async-taglib/#<code>&ltawait-error><code>)

It's good practice to make sure you have an uncaught exception handler for any Node.js app that will gracefully close any connections and shutdown the app.

Hope that helps, but let us know if you have any other specific questions. I'm going to go ahead and close this issue, but please feel free to add more comments below.
