### ISSUE TITLE
Why is the whitespace for <script>s preserved?

### ISSUE THREAD

**Issue by steebchen** [marko-js/marko#385]
It's obvious why the whitespace of `<pre>` tags is not removed, but why for `<script>` tags too? Normally, you minify javascript code too so I don't get why this is ignored by default. Is there any why to enable minification for the `<script>` tag globally? `require('marko/compiler').defaultOptions.preserveWhitespace = true` sadly only does this globally, but if I have a `<pre>` tag it's displaying incorrectly. Is there a way to do this programmatically instead of a .json config file?

**Comment by patrick-steele-idem** [comment]
It is not safe to remove whitespace inside a `<script>` because the code inside a `<script>` tag is not HTML rules so we cannot use the HTML whitespace removal rules. If marko were to remove whitespace inside `<script>` tags then there is a good chance that it would break the code. If you want to safely remove whitespace inside a `<script>` tag then you would need to use a JavaScript minifier (the performance would be really slow so you would not want to run the minifier for every request). 

If you want go advanced, you can create your own compile-time transform that removes whitespace that is appropriate for your use case.

Hopefully that answers your question, but please feel free to add more comments here if not.
