### ISSUE TITLE
handleFileModified warning or similar for unresolved path

### ISSUE THREAD

**Issue by sandro-pasquali** [marko-js/marko#387]
When using `require('marko/hot-reload').handleFileModified`, if a not-resolvable template path is passed there will be no warning (or other notification)

A very minor quibble, but this was related to a somewhat elusive bug in my code.

Maybe just a warning, or change the existing output from:

```
[marko/hot-reload] File modified: /cant/resolve/this/path/to/index.marko
```
to something like:
```
[marko/hot-reload] ERROR! cannot resolve template path: /cant/resolve/this/path/to/index.marko
```

**Comment by patrick-steele-idem** [comment]
I think that's a good suggestion, although I would probably use `WARNING` instead of `ERROR`. Would you be interested in submitting a PR to improve marko? Thanks for opening the issue.

NOTE: Marko v4 development is on master and Marko v3 is on the [v3 branch](https://github.com/marko-js/marko/tree/v3)
