### ISSUE TITLE
Allow whitespace in attribute value expressions not wrapped in parenthesis

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#424]
This change allows whitespace in complex expressions such as the following:

``` xml
<assign name=lastName.toUpperCase() + ', ' + firstName.toLowerCase()/>
```

See related PR for `htmljs-parser`: [htmljs-parser PR #37](https://github.com/philidem/htmljs-parser/pull/37)

**Comment by Hesulan** [comment]
I'm more than a little hesitant about this... I do see how it could be useful, but considering what little would be gained (expression whitespace already works inside parenthesis, and is arguably easier to read most of the time) versus the potential costs (reserved operator names, inconsistent behavior, potential ambiguity, etc.), I feel this needs more discussion, especially since it would likely affect any future enhancements which deal with or depend on whitespace behavior.

Perhaps if this were to be opt-in, and only enabled by default on certain tags like `<var>` and `<assign>`? I would love to see something like that, and it would virtually eliminate the problems I mentioned (you can pretty much assume that anything on a `<var>` tag after the `=` is part of the value expression).

**Comment by patrick-steele-idem** [comment]
Only handling this for the `var` and `assign` tag is a reasonable suggestion. I think I might be okay with that. What do you think @mlrawlings ?

**Comment by Hesulan** [comment]
I haven't peeked at the code yet, but if this could be a some sort of opt-in flag on the tag definition (or renderer, or AST node, or wherever it would fit best), then any other tags - possibly even user-made taglibs - could simply enable this "loose whitespace" support with relative ease without changing the expected behavior for anything else.

**Comment by patrick-steele-idem** [comment]
The parser does support entering into new parsing modes based on the tag name so that is certainly an option. It's also possible that the `var` could handle making sense of the separate attributes (divided by spaces) and group things back together, but that might get messy.

**Comment by Hesulan** [comment]
I would much prefer a parsing mode switch based on the tag name, it seems like it would be much less messy and more reusable than having each tag manually stitch everything back together, or it might even be as simple as adding a couple of flags to the commit from the related PR. Is the parser able to read a config parameter from somewhere user-accessible, like the `marko.json` definition, or would the tag names which support this need to be hard-coded?

**Comment by mlrawlings** [comment]
@Hesulan It's certainly safer to make this apply to only `var`/`assign` because there is no possibility that an operator in a variable name is valid.  However, I'm concerned that there may be confusion if I can do `<var sum = 1 + 2 />` but not `<counter start = x + 1 />`.  

@philidem also suggested that if we were to do this it should be across the board at the parser level.

### Reasoning

I certainly understand that this can impact readability:

```html
<custom-tag count = 1 + 2 + 3 class = foo style = styles.foo />
```
vs.
```html
<custom-tag count=(1 + 2 + 3) class=foo style=styles.foo />
```


However, I see the main reason for this is to be able to write code in `.marko` that looks like js:
```js
import { calc } from './helpers'

var sum = data.value + 5
var calculated = calc(data.value, 2)

<div>${calculated}</div>
```

### Another possibility

I don't know if this is a good idea, but I'll throw it out there:

What if we required comma separation when using whitespace around `=`:
```html
<custom-tag count = 1 + 2 + 3, class = foo, style = styles.foo />
```
Which actually lines up with JS pretty well:
```js
var count = 1 + 2 + 3, x = foo
```

@patrick-steele-idem and I had also talked about allowing a semicolon at the end of a concise tag:

```js
var count = 1 + 2 + 3, x = foo;
```

**Comment by austinkelleher** [comment]
Using comma separation is an interesting idea, I do like the fact that it aligns with JS. The down side is that it may cause confusion if it's only required when using whitespace.

**Comment by patrick-steele-idem** [comment]
Good discussion. After giving it some thought, I think the comma solution is the best option and it should be allowed for all tags (not just `var`/`assign`). The parser should be updated such that, when encountering a comma, would combine everything after an attribute `=` and before the `,` together to allow the following to work as expected:

```xml
<custom-tag count = 1 + 2 + 3, class = foo, style = styles.foo />
```

I think that provides a good balance to being like HTML (space-separated attributes), while also being like JavaScript.

Are we okay with the comma being used sometimes, but not all times for the same tag?:

```xml
<!-- commas sometimes: -->
<custom-tag count = 1 + 2 + 3, class = foo style = styles.foo />
```

The only possible edge case is that the comma was supposed to be part of the expression, but I can't think of any reason that would ever be the case.

Similarly, I am still in favor of allowing a `semicolon` to end a tag such that the following would be allowed:

```xml
<var foo=123, bar=456;/>
var baz=456;
```

Thoughts?

**Comment by patrick-steele-idem** [comment]
As a side note, a comma would allow the following in concise mode:

```
var foo=123,
      bar=456
```

The comma at the end of the line would make it clear that additional attributes are expected and the parser would say in the tag parsing mode even if the EOL is reached.

**Comment by mlrawlings** [comment]
@patrick-steele-idem What about if the last (or only) attribute has spaces?
```xml
<custom-tag count = 1 + 2 + 3 />
```

In concise mode, if we allow a semicolon as an indicator that this is the last space separated value, that could work:

```js
var foo,
    count = 1 + 2 + 3;
```

What if the comma/semicolon syntax was specific to concise mode?  We're trying to make things look more like JS, but there's nothing wrong with wrapping the value in parenthesis:
```xml
<custom-tag count = (1 + 2 + 3) />
```

**Comment by Hesulan** [comment]
I like the idea of the comma syntax being concise-specific. It already has more of a javascript-y vibe (actually python-y because of the significant indentation, but you get my point), while the standard syntax feels more like enhanced HTML, at least in my opinion. Also, my original concern was over allowing whitespace everywhere within value assignments without explicit boundaries; I can't think of any serious problems that allowing whitespace around the `=` might cause, aside from looking horrible when misused (`<tag foo = foo bar = bar baz = (baz + 1)/>`), but that can be said about almost anything.

As for only requiring commas sometimes, another possibility might be an all-or-nothing; if the tag contains values with whitespace, then there must be a comma between every attribute. As a side effect, that would also make it a bit easier to read, you would end up with either `tag foo=(1 + 2) bar=3 baz` or `tag foo = 1 + 2, bar=3, baz` instead of `tag foo = 1 + 2, bar=3 baz`.

**Comment by mlrawlings** [comment]
Patrick and I were just discussing this and realized that there could be some other issues:

### Text content on same line
Content on the same line would be an issue:
```js
tag baz = 3 - Hello, World;
```

*Is that `<tag baz=3>Hello, World;</tag>` or `<tag baz=(3 - Hello) World />`?*

### Multi-line values
Attribute value split across multiple lines:
```js
var foo = doSomething()
    .chain1
    .chain2
```
*Are those property accessors, or shorthand divs with classes?*

I suppose in this case it would be easy enough to say that multiline values ***must*** be wrapped in parenthesis.

**Comment by Hesulan** [comment]
Requiring a semicolon at the end with the comma syntax would solve that first part, then it would be either 'tag baz = 3; - Hello World;' -> '<tag baz = 3;>Hello World;</tag>' or 'tag baz = 3 - Hello World;' -> '<tag baz = 3 - Hello World;></tag>'.

**Comment by Hesulan** [comment]
typed that on my phone and I think it messed up the formatting... hopefully you know what I meant

**Comment by philidem** [comment]
**Here's my proposal:**

- When parsing _attribute value_, encountering whitespace followed by a character that is not a binary operator character (except for `-` in concise mode and `>` in HTML mode) will keep the parser in the _attribute value_ mode.
- When parsing _attribute value_ in _concise mode_, encountering `-` will switch to single line HTML mode (this is the current behavior)
- When parsing _attribute value_ in _HTML mode_, encountering `>` will end the current tag (this is the current behavior)
- When parsing _attribute name_ or _attribute value_, encountering a `,` (comma) will be treated as an attribute delimiter. All whitespace (including newline character) will be ignored after the comma is encountered until the next non-whitespace character is encountered. A mix of commas and whitespace can be used as delimiters within the same tag.
- When parsing _attribute name_ or _attribute value_, A `;` (semicolon) will always be treated as an attribute delimiter and will not be part of the attribute name or value. Unlike the comma, a semicolon cannot be used to wrap attributes across multiple lines. (I think we still need to discuss this more)

**Comment by Hesulan** [comment]
When in *concise mode*, could a `;` (semicolon) simply end the current tag like `>` does in *HTML mode*?

For example:
```
nav.navbar; ul
    li for(link in data.links); a href=link.href - ${link.title}
```
Would be shorthand for:
```
nav.navbar
    ul
        li for(link in data.links)
            a href=link.href - ${link.title}
```
or
```
<nav.navbar><ul>
    <li for(link in data.links)><a href=link.href>${link.title}</a></li>
</ul></nav>
```

**Comment by mindeavor** [comment]
I agree with restricting this feature to concise syntax. The HTML-JS syntax is naturally more verbose, and with that verbosity you gain explicitness.

    <assign name=( lastName.toUpperCase() + ', ' + firstName.toLowerCase() ) />

This looks nice and readable to me. I have no desire to remove these parenthesis, just as I have no desire to remove general closing tags :)

**Comment by mlrawlings** [comment]
I just made a PR implementing this and some related parser updates. I'd love some feedback from everyone that has contributed to this discussion. https://github.com/philidem/htmljs-parser/pull/42

**Comment by patrick-steele-idem** [comment]
Fixed with upgrade to `htmljs-parser@^2`
