### ISSUE TITLE
Promises/A+ Compliance

### ISSUE THREAD

**Issue by Hesulan** [marko-js/marko#439]
While digging around in the compiler just now I noticed that some of the code is *not* Promises/A+ compliant, specifically the `<await>` tag. These are mostly edge-cases, and will *probably* never break anything, but here's what I found:

* The promise resolution procedure must only access the `.then` property once. So instead of `if (typeof promise.then === 'function') { promise.then(...); }` it should use `var then = promise.then; if (typeof then === 'function') { then.call(promise, ...); }`

* If attempting to retrieve the `.then` property throws an error, then the error must be caught and the resulting promise must be rejected with the error as the reason. (It currently isn't being caught.)

* The `.catch(onRejected)` method is neither defined nor required by the specification, it's simply a convenient alias for `.then(null, onRejected)` which *most* promise implementations *choose* to provide. 

Those are just the things I happened to remember, there are probably a few other technicalities that I've forgotten about since I last read through the spec. I'll try to work on this when I get the chance but until then I thought I should post this somewhere. I'll also keep an eye out for other places in the code that might handle Promises incorrectly and add them here.

Promises/A+ Specification: https://promisesaplus.com/

**Comment by Hesulan** [comment]
This also raises an interesting question: Should Marko actually be trying to handle Promise resolution directly, or would it be better to rely on a native/polyfilled `Promise` implementation? It looks like that's what #251 is currently doing.

If Marko is to handle "thenables" directly, then I would be in favor of adding a common helper utility for it - which would essentially be a built-in polyfill - so that each tag or feature which needs to handle Promise resolution won't end up re-implementing their own non-compliant handling code. I have enough experience writing spec-compliant thenables to do that, but I would much prefer letting a dedicated `Promise` implementation handle it.

**Comment by Hesulan** [comment]
Quick update: Since #251 only applies when the user explicitly calls the `.then` method, it's considered a special case. The `<await>` tag, however, needs to be usable in pre-ES5 environments, which leaves either a built-in polyfill or just more compliant handling code as the only options.

However, I've also noticed one other issue: The `<await>` tag currently accepts either a value, a Promise, or a node-style function (last argument is an error-first callback). I'll continue working on this under the assumption that we want the `<await>` tag to continue to handle node-style functions, but be aware that this behavior defies the Promises/A+ specification.

**Comment by patrick-steele-idem** [comment]
Here are some replies:

> The promise resolution procedure must only access the `.then` property once.

Why do you say that?

> If attempting to retrieve the `.then` property throws an error, then the error must be caught and the resulting promise must be rejected with the error as the reason. (It currently isn't being caught.)

I don't see a need for this since accessing the `.then` property should throw an error if it is a `Promise`.

> The `.catch(onRejected)` method is neither defined nor required by the specification

`catch` is part of the specification: http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch

While we could fall back to `.then(null, onRejected)` in the case of no `.catch()`/`.fail()` method, but I'm not seeing a need for that.

> Should Marko actually be trying to handle Promise resolution directly, or would it be better to rely on a native/polyfilled `Promise` implementation?

Marko should rely exclusively on the native `Promise` implementation and that is what is happening now on `master`. 

> The `<await>` tag, however, needs to be usable in pre-ES5 environments, which leaves either a built-in polyfill or just more compliant handling code as the only options.

In the case of the `<await>` tag, Marko is never actually creating a `Promise` (it is just continuing the `Promise` chain of an existing `Promise`). In an ES5 environment you would need to use a native `Promise` polyfill or use a third-party library (`bluebird`, `q, etc.) to create the `Promise` instance.

> However, I've also noticed one other issue: The `<await>` tag currently accepts either a value, a Promise, or a node-style function (last argument is an error-first callback).

The `<await>` tag accepts a `Promise`, a Node.js-style callback function or a "resolved" object. I'm not seeing a problem with this approach.

---

Marko has some logic to handle old-style `Promise` objects, but for the most part we are assuming that a `ES6`-style `Promise` is being provided: file:///Users/psteeleidem/Library/Application%20Support/Dash/DocSets/JavaScript/JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Promise.html

I'm not seeing a need to change anything related to the comments above. We still need to decide if we want to wrap the `render(data)` call with a `try...catch` to reject the promise. Currently, we don't have a single `try...catch` block in `marko` for performance reasons (functions with `try...catch` are not optimized by V8)

**Comment by Hesulan** [comment]
I'm basing these comments solely on the Promises/A+ specification, which defines the behavior and requirements of the ".then" method common to all implementations. ECMAScript defines the ".catch" method for native implementations, but libraries have no obligation whatsoever to include it. The second argument to ".then", however, *is* explicitly defined and must be supported by all implementations.

The ".then" only being accessed once is a subtle requirement, I wouldn't have even known about it if not for the 'promises-aplus-tests' package. To be honest, it probably won't ever affect anything.

Currently, if attempting to access ".then" throws an error, it is simply thrown. It should instead cause the resulting Promise to be rejected.

The Promises/A+ specification explicitly defines how to resolve an object *or function* - the "await" tag resolves functions in a non-compliant way. I believe the inconsistency is acceptable as long as users are aware of it, I just felt it was worth mentioning.

Ultimately, the changes I'm proposing would only really affect edge-cases, like weird (but still compliant) implementations that don't have a ".catch" method, or can't handle synchronously-thrown errors.

**Comment by patrick-steele-idem** [comment]
@Hesulan these are great points, but I think we should focus on the `Promise` specification as defined as part of EcmaScript and implemented by Node.js and browsers (and polyfills). I would welcome as many tests as possible to make sure the Marko implementation holds up to all edge cases for the native `Promise` implementation, a popular `Promise` polyfill and maybe `q` and `bluebird`. For example, we need to make sure we have a test case for a synchronous error when rendering a template and using `.then()`/`.catch()`. Does that seem reasonable?

**Comment by Hesulan** [comment]
I suppose most of those technicalities likely won't ever affect anything, so as long as the test cases are fairly thorough we should be fine. Though I do still suggest relying on the second argument to `.then`, as it's explicitly defined and used by every implementation that's even remotely compliant, while `.catch` is completely optional for third-party libraries.
