### ISSUE TITLE
Extend another marko.json

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#440]
Add support for an `extends` property to `marko.json`:
```js
{
    "<foo>": {
        "transformer":"./foo.transformer.js"
    },
    "extends": [ 
        "bar", // extend a node_module (gets marko.json from the root of the package)
        "./other/marko.json" // extend another marko.json file
    ]
}
```

This would allow a package to "export" tags from packages it depends on.

Open to other names: `includes`, `imports`, etc.

**Comment by Hesulan** [comment]
I'm not sure I understand. It sounds like you're saying this would cause "bar/marko.json" and "./other/marko.json" to behave as though they were directly written in the root "marko.json", correct? What would that affect? Bundling? Module loading? In other words, could you give an example use-case from the end user's perspective?

I can't see any reason not to implement this, I'm just a little unclear on the motivation to do so.

**Comment by mlrawlings** [comment]
The use case I'm thinking of is allowing one package to make the tags of another package available without the main application needing to depend directly on both.  

As an example, take your `let` and `const` package.  Maybe I want to create an `es6-taglib` package that would expose those tags as well as some others.

**Comment by Hesulan** [comment]
Ah, makes sense. I would suggest either "include(s)" or "import(s)", the word "extends" doesn't sound quite right for what this would be doing.

**Comment by patrick-steele-idem** [comment]
In theory this sounds good, but it becomes a problem if the other `marko.json` being extended belongs to a nested package dependency and not a `peerDependency`. Nested dependencies may get installed into a `node_modules/` directory of the package with the parent `marko.json` which can cause problems since the `marko` compiler needs to generate `require()` calls to those nested dependencies. If a tag is purely a compile-time tag then it is not an issue, but it would be a problem for runtime custom tags that need to be imported into compiled templates.

I'm not sure there is a strong enough need for this at the moment, but we can discuss some more.

**Comment by mlrawlings** [comment]
Looks like [`taglibImports`](https://github.com/marko-js/marko/blob/master/compiler/taglib-loader/loader-taglib.js#L200-L248) with a small tweak will already do this.
