### ISSUE TITLE
Recursive components

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#453]
In v3 there is an issue:

### `<foo/>`

_`index.js`:_
```js
module.exports = require('marko-widgets').defineComponent({
    template: require('./template.marko');
});
```

_`template.marko`:_
```html
<div w-bind>
     <if(data.children)>
         <foo(child) for(child in data.children)/>
     </if>
</div>
```

The `<foo/>` `index.js` references `template.marko` before it exports anything and `template.marko` references `index.js`, which ends up with the template getting an empty object instead of the renderer.

Hanging methods off the existing `exports` in `index.js` will fix this:
```js
var component = require('marko-widgets').defineComponent({
    template: require('./template.marko');
});
exports.renderer = component.renderer;
exports.render = component.render;
exports.renderSync = component.renderSync;
```

I'm pretty certain that v4 doesn't have this issue in the case that the template is the entry point, because the component does not reference the template.

**Comment by patrick-steele-idem** [comment]
The solution in V3 is to use `require.resolve('./template.marko')` to cause the template to be lazily loaded on first render. This is not an issue in Marko v4. I don't think it would make sense to try to fix this in V3 since there is a workaround. Closing this issue, but feel free to add comments if you disagree.
