### ISSUE TITLE
Destucting <import> compiles wrong in 4.0-beta.3 when import name is the same as module name

### ISSUE THREAD

**Issue by tinovyatkin** [marko-js/marko#464]
Hello,

Destructing `import` like following compiles correctly:

```html
<import { readFileSync } from 'fs' />
```
results to following:
```javascript
   fs = require("fs"),
   readFileSync = fs.readFileSync,
```

However, destructing imports, like
```html
<import { asset } from '../../../shared/marko/asset' />
```

results in wrong compilation:
```javascript
asset = require("../../../shared/marko/asset"),
asset2 = asset.asset,
```

Side note: which version of Node Marko 4 is targeting? Why not current LTS (Node 6) and just keep destruction intact, as well as use `const` instead of `var`?

**Comment by Hesulan** [comment]
@tinovyatkin The compiler currently requires ES6 (Node 4+), but all built-in taglibs are currently designed to compile into ES5-compatible code (ES6+ tags *may* eventually be included if there's enough interest - see #428).

The `asset2` assignment is definitely an oversight, it's *supposed* to prevent automated naming collisions but in this case appears to be renaming the wrong one.

**Comment by tinovyatkin** [comment]
As far I see <import> compiles into require and it's no way browser compatible with our without destruction...

**Comment by Hesulan** [comment]
Most modern client-side code depends on a third-party library like `browserify` to implement CommonJS `require`, and Marko is no exception. In other words, `require()` most certainly *is* browser-compatible.

**Comment by tinovyatkin** [comment]
@Hesulan I'm sorry to say, but there is no logic to say `can be rendered in all modern browsers without needing to be transpiled` and then `require() most certainly is browser-compatible`. No, it's not. There is no browsers on the planet that understand `require` without transpilation / compilation / whatever you want to call it. So, the question still remain - why introduce new tag that have no way (a part of static inlining) to compile into ES5 and trying to do so?

**Comment by Hesulan** [comment]
@tinovyatkin Marko and Marko Widgets run in the current versions of all major browsers without any transpiling. While `require()` certainly isn't native, it's considered a dependency, or at worst a polyfill. Native destructuring would require the entire file to be transpiled, and there's no reason to do that here since the current ES5 implementation already works perfectly aside from this bug.

Don't get me wrong, I'm certainly not against ES6+ features in the core taglibs; in fact, if you look at the PR I linked to, you'll see that I've personally been working on exactly that. But `<import>` is a *really* useful tag for all environments, and in this case the cost would far outweigh the gain.

**Comment by scttdavs** [comment]
yeah as already stated, this is marko trying to avoid naming collisions. The import parser could use: 
https://github.com/marko-js/marko/blob/master/compiler/util/safeVarName.js
to generate a safe name, but it would still fail for:
```html
<import { asset } from 'asset' />
```
 A quick fix would be to just add a namespace to that function as well, so in the above case it would output:
```javascript
var m__asset = require("asset"),
    asset = m__asset.asset;
```
The namespace could be anything pretty unique, but you could technically still encounter the bug if you know it or miraculously name your var the same. Otherwise, I don't see an obvious solution other than digging into marko's naming collision logic.
@patrick-steele-idem @mlrawlings Thoughts?

**Comment by Hesulan** [comment]
@scttdavs Another option might be to use one of the reserved template variable names ('data' or 'out') to temporarily store each module:
```js
var data = require("asset");
var asset = data.asset;
var data = ...
```
If someone needs to `<import { data as data } from 'asset' />` then they're probably doing something wrong, since it will get overwritten by `render(data, out)` anyway.

**Comment by tinovyatkin** [comment]
If it's a vote, I certainly hope Marko developers will decide to just keep destruction intact and document that fact. It's a shame that nowadays development frameworks sometimes trying to pretend they are for people who don't know how to code. 
You are introducing new tag with `ES6 like imports`, requiring Node 4 for compiler and trying to reinvent the wheel of destruction?

Why not `<import { asset } from 'asset'>` => `const { asset } = require('asset')`?
What exactly is bad with this approach to a new, ES6-like tag? Marko is trying hard to make resulting `.marko.js` readable, and introducing namespaces, generated names, etc, no way helps that..

**Comment by patrick-steele-idem** [comment]
@tinovyatkin For now, we want Marko templates to compile to ES5-compatible code since compiled templates can either be loaded in the browser or on the server. On the server, the compiler requires Node.js v4+, but the runtime is ES5-compatible and works with IE9+ and all other modern browsers.

As it stands now, `import`/`export` is not finalized and that syntax is not natively supported by Node.js and browsers. We don't want to require the use of Babel for any of the core tags that we document as part of Marko so that means that Marko need to transpile `import`/`export` to something that is widely supported and since we are going to transpile we might as well make the code ES5-compatible for improved compatibility.

Regarding transpiling the following:

```xml
<import { asset } from '../../../shared/marko/asset' />
```

Something similar to the following would work:

```javascript
var asset_module = require("../../../shared/marko/asset"),
var asset = asset_module.asset,
```

A single `_` in the variable name should be sufficient for avoiding collisions since developers typically don't use `_` in variable names. However, we can make the variable as long or as short as we want since it won't matter after the code is minified.

At the moment, I am currently swamped. If anyone wants to work on fixing the compiled code for the `<import>` tag please let me know. Thanks in advance.

**Comment by mlrawlings** [comment]
I _think_ this is as simple appending `_module` or something [here](https://github.com/marko-js/marko/blob/8f4c884fba1d7460690de989d292968c613130cc/taglibs/core/util/parseImport.js#L33).

Along with the change I'd like to see an additional test making sure something like the following produces a sane output:

```html
<import { asset as test } from "./test1/asset"/>
<import { asset } from "./test2/asset"/>
```

**Comment by Hesulan** [comment]
It just occurred to me that `require()` is expected to cache loaded modules:
```
var foo = require('./foo').foo;
var bar = require('./foo').bar;
```
Not very pretty, but perhaps more readable, and definitely more collision-proof. Thoughts?

**Comment by patrick-steele-idem** [comment]
> It just occurred to me that `require()` is expected to cache loaded modules:
> ```
> var foo = require('./foo').foo;
> var bar = require('./foo').bar;
> ```
> Not very pretty, but perhaps more readable, and definitely more collision-proof. Thoughts?

Other then still being slightly slower to execute, that code wouldn't minify as well so I would still like to see each module only be required once.

**Comment by Hesulan** [comment]
@patrick-steele-idem Good point. I don't think execution speed would really be a problem since all of this is happening once when the module is first loaded, but minifying would be, especially with lasso since the url becomes a lot longer...

The `_module` suffix solution should work just fine, as long as it's well documented.
