### ISSUE TITLE
Interoperability with React

### ISSUE THREAD

**Issue by leonth** [marko-js/marko#488]
### Description
There are 2 use cases for this:
1. People who want to primarily use React but want to have some (perhaps presentational-only) components written in marko.
2. People who use primarily marko templates but want to use React (i.e. render React components) in some dynamic pages (this is marko-widget's use case, but let's say that a hype-driven tech lead wants React for dynamic stuff by all means necessary).

### Context
1. We need an easy-to-use template system as we have freelancers churning out new templates that come and go every once in a while. Here, marko seems like a good fit.
2. Static parts need to be easily integrated with non-React JS libraries like jQuery. Dynamic parts are written in React.
3. The team has invested quite a bit in the React ecosystem, so we are not keen on introducing something like marko-widgets.
4. We are concerned with the performance of server-side React rendering.

From reasons above, [react-templates](https://github.com/wix/react-templates) almost made it but not quite (mainly due to reasons 2 and 4).

After this, marko users can also tap into the larger React ecosystem for things like integration, off-the-shelf components.

### Possible Implementation
The 2 use cases boils down to these requirements:
1. Render React components in marko perhaps using taglib. (e.g. `<div><react-component prop1="a" prop2="b"/></div>`) This react root should be able to have isomorphic/universal rendering (meaning it can gain the ability to be re-rendered client-side, if the developer chooses to include react on client side).
2. Render marko components as React components. (e.g. in JSX: `<div><MarkoTemplate template={require("a/b.marko")} /></div>`) 

Both seems very doable to me, but would like some input on potential headaches.

1. This can (should?) be an optional module / custom taglib.
2. Each `<react-component/>` tag can live as a separate React root. Most SPAs only have one root that renders the whole page, but this usually won't be the case if rendering starts from marko. 

### Open Questions
1. Do we need to handle children tags inside templates (the content inside `MarkoTemplate`)?
2. Need to figure out how to use singleton store (redux etc) for multiple React roots.
3. Building SPAs will be difficult if we have multiple react roots in a page, but this may be a concern more for React and not for marko.

### Is this something you're interested in working on?
Yes

**Comment by patrick-steele-idem** [comment]
Just some initial thoughts:

- It's already possible to embed a React component in a Marko component but we can definitely provide things to make this more seamless
- I'm definitely open to ideas on improving operability (in addition to the reasons you mentioned, but also because I would like to make it easier for teams to try or transition to Marko)
- If you use React when rendering on the server then you will have no choice but to rerender everything in the browser since React requires this (Marko does not require this)
- Seamless interoperability can become complex when trying to support both server-side and client-side rendering, but I think it is completely doable
- It seems reasonable to create a generic adapter component for embedding a React component in Marko (and vice versa)
- It's possible to translate a rendered Marko VDOM tree to a React VDOM tree with a performance hit (via tree traversal of the Marko VDOM output)
- Alternatively, a Marko component can be rendered and mounted during the `componentDidUpdate()` lifecycle method (client-side only)
- Usage ideas:

_Marko component with embedded React component (using Marko v4):_

```xml
import MyReactComponent from "./MyReactComponent";

<div>
  <react-component(MyReactComponent) name="Frank" age=30/>
</div>
```

React component with embedded Marko component:_

```jsx
import myMarkoComponent from "./my-marko-component";

// ...

return (<div>
  <Marko component={myMarkoComponent} name="Frank" age={30}/>
</div>)
```

I would to hear some more thoughts from others, but I just wanted to share my initial thoughts. Thanks for opening the issue.

**Comment by mindeavor** [comment]
I think the best solution long-term would be to have Marko have seamless interoperability with custom elements. That way, react / mithril / any library will be able to work without any extra work from marko.

For research, [server-components](https://github.com/pimterry/server-components) has done some work in this area.

**Comment by patrick-steele-idem** [comment]
@mindeavor there have been some conversations about providing an adapter to support registering Marko UI components as Web Component custom elements, but we have not done anything further. After the v4 release we should do more exploration to see what is possible and capture it in our ROADMAP. Right now, the Marko v4 release is our top priority and we hope to get that finalized soon :)

**Comment by leonth** [comment]
Thanks for the inputs. I believe v4 is just around the corner looking at the beta releases coming out these few days?

> It's possible to translate a rendered Marko VDOM tree to a React VDOM tree with a performance hit (via tree traversal of the Marko VDOM output)

This is what I pondered on as well - there is something similar for handlebars: https://github.com/stevenvachon/handlebars-react I don't know much about marko internals but maybe translating parsed AST to React VDOM directly can be a better approach?

> Alternatively, a Marko component can be rendered and mounted during the componentDidUpdate() lifecycle method (client-side only)

CMIIW, but I think if we render a new react root in `componentDidUpdate` the VDOM diffing would never work because it is a fresh re-render each time. This should be much simpler to implement though, as compared to VDOM translation.
