### ISSUE TITLE
include() does not default to include(data.renderBody)

### ISSUE THREAD

**Issue by ianvonholt** [marko-js/marko#524]
I've been following the 4.0 milestone, however I'm getting the following error: 

```
Error: An error occurred while trying to compile template at path "site/components/hero-image/index.marko". Error(s) in template:
1) [site/components/hero-image/index.marko:3:2] The include attribute must have an argument. For example: include("./target.marko") or include(data.renderBody)
```

However, with respect to https://github.com/marko-js/marko/issues/418, examples and notes illustrate the following approach:

```include()``` is the same as ```include(data.renderBody)```

Commit https://github.com/marko-js/marko/commit/306e19b88e9e305c83b9da1b4eab3fa8e028ee8f introduces the body-slot tag. 

Should we be using body-slot instead of the deprecated w-body tag, or transition to include(data.renderBody)?

**Comment by Hesulan** [comment]
The `<body-slot>` tag was removed shortly after being added, and `include()` with no arguments was disallowed. I believe `include(data.renderBody)` is now the recommended way to do this.

You can also do something like:
```
<html>
    <head>
        <include(data.head) />
    </head>
    <body>
        <include(data.body || data.renderBody) />
    </body>
</html>
```
Then use it like:
```
<include('./layout.marko')>
    <@head>
        <title>Foo!</title>
    </@head>
    <@body>
        Foo!
    </@body>
</include>
```
or
```
<include('./layout.marko')>
    Foo!
</include>
```

**Comment by patrick-steele-idem** [comment]
Related: [#492 - Deprecate w-body in favor of include](https://github.com/marko-js/marko/issues/492) (there is a collapsed "Other Options Considered" section that has relevant details)

#418 is out-of-date after further discussions were made as part of #492. The feedback that we received was that no one really liked the usage of `<include()>` with an empty argument since it didn't make it clear what exactly was being included.  We settled on dropping `w-body`, and dropping the temporarily introduced `body-slot` attribute/tag, in favor of a universal `<include(target)/>` tag. We still need to capture this correctly in the final release notes and documentation, but for now [#492 - Deprecate w-body in favor of include](https://github.com/marko-js/marko/issues/492) contains the latest docs for this feature.

Hope that clarifies. While we want to avoid changes at this point, nothing is set in stone so if you have any thoughts or concerns then please share. I'm closing the issue but please feel free to add more comments here.

**Comment by ianvonholt** [comment]
@patrick-steele-idem Thank You. 

I have a all of the code using the proper `include(target)` due to the various research through the issues list. However, it wasn't readily apparent which direction was actually correct and I wanted a bit more feedback on what was the final decision.
