### ISSUE TITLE
[v4] Click binding lost after client-side redraw

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#527]
## Bug Report

On first render, an `on-click` handler works perfectly on a first button. After a redraw (upon clicking the "I already have an account" button), the new button does not receive the click binding like the first.

### Context

```html
<script>
module.exports = {
  onInput(attrs) {
    this.state = { type: 'signup' }
  },
  setType(type) {
    this.state.type = type
  }
}
</script>

<form class="session-panel">

  <if(state.type === 'signup')>
    <h3>Sign Up for an Account:</h3>
    <input type="text" name="email" placeholder="Email" />
    <button type="submit">Sign Up</button>
    <button class="secondary" on-click('setType', 'signin')>I already have an account</button>
  </if>

  <else>
    <h3>Sign In:</h3>
    <input type="text" name="email" placeholder="Email" />
    <input type="password" name="password" placeholder="Password" />
    <button type="submit">Sign Up</button>
    <button class="secondary" on-click('setType', 'signup')>I don't have an account</button>
  </else>
</form>
```

<details><summary>Additional Info</summary>

### Your Environment

* Version used: v4.0.0-rc.1
* Environment name and version: Chrome 54, node 6.9.1
* Operating System and version (desktop or mobile): OS X
</details>

**Comment by patrick-steele-idem** [comment]
Let me see if I can reproduce. Taking a look. Thanks for reporting the problem.

**Comment by patrick-steele-idem** [comment]
I am not able to reproduce @mindeavor. When I click on the "I already have an account" button, the form toggles and I am able to click the corresponding button to toggle back and everything appears to be working as expected.

**Comment by mindeavor** [comment]
Hmm. Can you confirm your URL bar has not changed? Clicking the button the second time submits the form, which does revert it back to the original state.

**Comment by mindeavor** [comment]
Ohh hmm, I see. I changed the `<form>` tag to a `<div>` tag and it worked. But then that means marko is preventing the form from submitting for the first click, but not the second?

**Comment by patrick-steele-idem** [comment]
As part of the HTML spec, the `<button>` element defaults to a `<button type="submit">` button and will submit the form when clicked. If you change to `<button type="button">` then your form will work as expected and clicking the button will not submit the form. That should resolve the issue with no changes to marko required.

**Comment by mindeavor** [comment]
I understand that, and know how to work around my problem now. But isn't it strange that marko prevents the first button click from submitting the form, but not the second? According to the HTML spec marko should not be preventing the submit at all, correct? That's what confused me in the first place; because of the current behavior, I had assumed marko was preventing the form *for* me as a feature.

It's probably a small thing and might not warrant a fix (who would want an `on-click` **and** want the form to submit?), but I wanted to throw that out there for the record, in case anyone else runs into it in the future.

**Comment by patrick-steele-idem** [comment]
Fair point. Let me take a closer look to figure out why the first time the button clicks it does not submit the form.

**Comment by patrick-steele-idem** [comment]
We investigated some more and everything is working correctly, but there was an interesting side effect related to DOM diffing/patching that was causing the observed behavior. It just so happened that when clicking on the submit button for the first time, the DOM diffing/patching algorithm ends up detaching the clicked submit button from the DOM and this causes the browser to not submit the form. Currently, the UI is rerendered after delegating to all DOM event handlers so the DOM diffing/patching happens before the browser has a chance to handle the event in the default way. If you are wondering why the submit button was detached, it was because of the inserted `<input type="password">` element that was in the `<else>` block.

With that said, we did decide to make a chance to Marko that would avoid this problem. Currently, we update the DOM after processing all of the event handlers. We decided to delay the updating of the DOM using `setImmediate` or the browser equivalent. That is, all updates to the DOM will be batched on the next tick of the browser.
