### ISSUE TITLE
[v4] Absorb rest of features in marko-magic?

### ISSUE THREAD

**Issue by gilbert** [marko-js/marko#536]
The `marko-magic` module enables game changing auto-detection for asset dependencies. I had thought that marko would absorb it all for v4, but it looks like `marko-magic` is still necessary for some lasso-related things.

For example, in the [ui-components-playground](https://github.com/marko-js-samples/ui-components-playground) I still see:

- `<lasso-head/>` and `<lasso-body/>` in the layout
- a `browser.json` for declaring a `style.less` dependency
- a `browser.json` for the home page, declaring the `<app>` and other browser dependencies.

Since marko is already at `v4.0.0-rc3`, I need to ask: are you all planning to release without the asset detection features?

**Comment by mlrawlings** [comment]
So technically, these changes will be outside of Marko and be a part of the Lasso taglib.  While Marko is at an RC, there is still some things to update in supporting package and this is one.

However, I would like to have some discussion around the Marko magic approach and if we should make all of it mainstream.  

Particularly, I have concerns about automatically injecting the Lasso head and body tags automatically.  I wonder if it's a bit weird that, since we use `head` as an injection point, that if there is no head tag you won't get any styles.
Likewise for body.

**Comment by mindeavor** [comment]
I think requiring `<lasso-head/>` and `<lasso-body/>` is acceptable. It's the json files that I'm mostly concerned about; I want to write as few of those as possible :)

**Comment by mlrawlings** [comment]
The `@lasso/marko-taglib` does a lot of what marko-magic did now: 
- `browser.json` is not needed, but if it exists it is automatically picked up at the component level (so there doesn't need to be an additional top-level `browser.json` to reference it)
- `<lasso-head>` is auto injected at the end of `<head>`
- `<lasso-body>` is auto injected at the end of `<body>`
- `<lasso-page>` is optional
