### ISSUE TITLE
Marko 4 widget inline output support

### ISSUE THREAD

**Issue by Eldar-X** [marko-js/marko#537]
## Inline output support for marko widgets

While marko widget now part of marko.js how about add support for printing compiled output of widgets inline to template file without bundlers? 

I think it's important feature because widgets must be independent from 3rd part tools but can provide support for them.

**Comment by mlrawlings** [comment]
Can you explain a bit more? I'm not clear on what you are suggesting.

**Comment by Eldar-X** [comment]
Now for working with marko we must bundle output of widget yes? But why we can't just put output of widget into html between script tag? for example we have onclick listener in our widget why just not put in html? I know that bundled js have some better features but it also may be not bad

**Comment by Hesulan** [comment]
Even the simplest widget depends on the `marko/widgets` runtime, which needs to be bundled anyway. It *might* be possible to add a compiler optimization to recognize this edge case and use plain JS instead, but that could easily break something. Alternatively, you could just add `<script>document.getElementById(...).addEventListener(...);</script>` yourself or even write a custom attribute transformer.

If you're just wanting specific widgets to be embedded in the page rather than included in the main bundle, most bundlers provide a way to do that. Lasso, for example:
```json
{
     "dependencies": [
        { "require": "./component.js", "inline": true }
    ]
}
```
Which results in something like:
```html
<body>
    ...
    <script src="/static/page-1ae394d6.js"></script>
    <script>
        /* component.js */
    </script>
</body>
```
