### ISSUE TITLE
"Symbol()" used in compiled code for browser, not supported by IE - Marko v4

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#554]
Not sure if this is known, but I was testing a simple Marko 4 Widget in IE and it fails when trying to call new Symbol(). This doesn't appear to be supported in IE 11. As you can see [here ](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol) Symbol isn't supported on any IE versions. Is this intended?

Is it expected that we need to pollyfill fill this?

**Comment by jasonmacdonald** [comment]
Promise is also missing from compiled bundle. :(

**Comment by patrick-steele-idem** [comment]
@jasonmacdonald can you please point to the code? `Symbol()` should be used in browser code and all of our tests are running in a very older version of V8 that doesn't support `Symbol` so I would not expect `Symbol` to be used. Also, which JS module bundler are you using (Lasso, webpack, etc.)?

**Comment by jasonmacdonald** [comment]
Here's the snippet where it appears...

```
},{}],49:[function(require,module,exports){
var KEY = Symbol();

function UniqueId(out) {
    this.prefix = out.global.widgetIdPrefix || 'w';
    this.nextId = 0;
}

function nextWidgetId(out) {
    var global = out.global;

    var idProvider = global[KEY] ||
        (global[KEY] = new UniqueId(out));

    return idProvider.prefix + (idProvider.nextId++);
}
```

**Comment by jasonmacdonald** [comment]
Nope, looks like it's coming from widgets/utils.js

**Comment by patrick-steele-idem** [comment]
There is a "widgets/util.js" and a "widgets/util-browser.js". We remap the former to the latter by putting a `browser` field in the `package.json` file: https://github.com/marko-js/marko/blob/44c38e74ad1a0c515ab96a05169f9c096678a3c2/widgets/package.json#L6

All JavaScript module bundlers (including Browserify, rollup, lasso, webpack, etc.) should respect the `browser` field. If you can provide a simple app to reproduce the problem with `browserify` that would be helpful. It could be a bug in browserify or it could be some strange combination of things. We should definitely investigate because browserify is supported.

**Comment by jasonmacdonald** [comment]
I switched over to Webpack and the issue seems to have gone away. However, if I can find a few mins I'll put together a simple project to show the issue. I'll close this for now and update if I can put something together,

**Comment by Hesulan** [comment]
@jasonmacdonald Just wanted to add, because you mentioned `Promise` not being bundled: Marko doesn't provide a Promise polyfill, and as far as I know the only parts of Marko that require a global `Promise` object are the AsyncStream's `.then()` and `.catch()` methods, and only if you choose to call them.
