### ISSUE TITLE
class tag is used for components only

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko#559]
The `class` tag currently supports creating a component when anonymous:
```jsx
class {
   constructor() {}
}
```
But creates a normal JS class when it has a name:
```jsx
class Foo {
   constructor() {}
}
```

We want to remove the second functionality.  It will _always_ create a component's class and you can optionally name that class.

**Comment by jasonmacdonald** [comment]
Hope I'm not hi-jacking the thread here, but on the topic of Classes, it seems you cannot use the extend keyword. If I make a component using a class that extends another class, it fails due to a instance check "_classCallCheck" where the instance is the Widget class, but it's checking for the Constructor of the parent. I get a failure of "cannot call a class as a function". This _seems_ to be caused by how Babel transpiles e6 code. Here's the relevant compiled code.

```
       function _classCallCheck(instance, Constructor) {
            if (!(instance instanceof Constructor)) {
                throw new TypeError("Cannot call a class as a function");
            }
        }
        var Test = function() {
            function Test() {
                _classCallCheck(this, Test);
            }
            _createClass(Test, [{
                key: "constrcutor",
                value: function constrcutor() {
                    console.log(parent);
                }
            }]);
            return Test;
        }();
        var Room = function(_Test) {
            _inherits(Room, _Test);
            function Room() {
                _classCallCheck(this, Room);
                return _possibleConstructorReturn(this, (Room.__proto__ || Object.getPrototypeOf(Room)).apply(this, arguments));
            }
            _createClass(Room, [{
                key: "onInput",
                value: function onInput(input) {
                    console.log("IT WORKED");
                }
            }]);
            return Room;
        }(Test);
        exports.default = Room;
        module.exports = exports["default"];
```

You can see the _classCallCheck is called twice, once for the child, once for the parent. It's the parent call that fails as the instance is "Widget" but the Constructor is "Room".

Is this the same issue as you mentioned above?

**Comment by Hesulan** [comment]
@jasonmacdonald Michael was talking about the `<class { ... } />` tag. None of the code generated by Marko currently compiles to anything greater than ES5, and javascript classes are ES6. Could babel be trying to compile the `.marko` template by mistake?

**Comment by jasonmacdonald** [comment]
For sure it's Babel compiling the es6 classes. I'm trying to use a class as my component definition. But, it seems to be Marko that is adding the _classCallCheck to the compiled component definition.

**Comment by Hesulan** [comment]
@jasonmacdonald I'm not quite sure what you mean, but using a class as a component definition is invalid. The `<class { ... } />` tag mentioned here is just a convenient syntax (with a bit of a misleading name), it doesn't *actually* generate an instantiable class.

**Comment by jasonmacdonald** [comment]
Sorry if I'm not being clear. I'm talking about Marko 4 widgets, defining a widget component using an ES6 Class instead of an Object. I'll start a different thread as this one isn't what I thought it was. Thanks!
