### ISSUE TITLE
getTemplateData not called with rc.12?

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko#561]
I just switched from rc 8 to 12 and my widgets getTemplateData method is no longer being called in any of my widgets. Was this removed for some reason?

**Comment by mlrawlings** [comment]
`getTemplateData` was necessary for v3 widgets because there was only `data` passed to the template and we needed some way to get `state` into the template as well as any input data you might have also needed.  

In v4, your template receives an `input` variable (also aliased as `data` for compatibility) and a separate `state` variable is available to your template if you set `this.state` in your component's class.  You can then access both `state` and `input` in your template.  You no longer need `getTemplateData` to make this data available to your template.  If you need to massage the input data that is being passed in as `input`, you can return a different value from `onInput`.

**Old:**
```js
module.exports = require('marko-widgets').defineComponent({
    template: require('./template.marko'),
    getInitialState(input) {
        return { count:0, color:input.color };
    },
    getTemplateData(state, input) {
        return state;
    },
    increment() {
        this.setState('count', this.state.count+1);
    }
})
```
```xml
<div w-bind>
    The current count is <span style={ color:data.color }>${data.count}</span>
    <button w-on-click="increment">+1</button>
</div>
```

**New:**
```jsx
class {
    constructor(input) {
        this.state = { count:0 };
    }
    increment() {
        this.state.count++;
    }
}

<div>
    The current count is <span style={ color:input.color }>${state.count}</span>
    <button on-click('increment')>+1</button>
</div>
```

**Comment by mlrawlings** [comment]
`getTemplateData` was technically part of the v3 style legacy widgets, but the code was so intermixed that you could still use certain legacy methods with the new components. That code has now been split out - is there still a need for it, or was it just surprising?

**Comment by patrick-steele-idem** [comment]
I wouldn't recommend it, but you could do the following:

```html
import { getTemplateData } from './component';

$ var data = getTemplateData(state, input);

<div>
    Hello ${data.name}!
</div>
```

**Comment by jasonmacdonald** [comment]
I have no problems with it being removed, just didn't realize it was, so it broke my code when I moved form rc 8 to 12. I couldn't tell if it was a bug or intended. I tried looking at the revisions, but couldn't make heads or tales of where the change actually happened. :)

I was only using it because the [Roadmap ](https://github.com/marko-js/marko/blob/master/ROADMAP.md) under heading **New widget lifecycle methods**  shows the getTemplateData method in the **new** list. So I thought I was supposed to be using it. :) I guess the roadmap doc just needs to be updated to remove it. 

Thanks for confirming.
