### ISSUE TITLE
[v4] Marko translates `null` to `undefined` when setting state

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#566]
## Bug Report

If you set `this.state.x = null`, then it actually gets set to `undefined` instead.

### Context

```jsx
class {
  onInput(props) {
    this.state = { mood: 'blissful' }
  }
  setMood(m) {
    console.log("Setting mood:", m)
    this.state.mood = m
    console.log("New mood:", this.state.mood)
  }
}

<div>
  <!-- JSON.stringify(null) should output "null" -->
  <p>Current mood: ${ JSON.stringify(state.mood) || "confused" }</p>
  <button on-click('setMood', 'happy')>Make me happy</button>
  <button on-click('setMood', null)>Make me null</button>
</div>
```

### Expected Behavior

Clicking "Make me null" should display `"null"` on the page.

### Actual Behavior

Clicking "Make me null" displays an empty string instead (the result of interpolating `undefined`)

<details><summary>Additional Info</summary>

### Your Environment

* Version used: rc.12
* Environment name and version: Chrome 55
</details>

**Comment by patrick-steele-idem** [comment]
Marko intentionally normalizes `null` to be `undefined` when assigning a value to a state property: https://github.com/marko-js/marko/blob/ffdc91382fb41484585b60ea98f840d3f8f5b25f/widgets/State.js#L68-L71

There's also the caveat that state properties with a value of `undefined` get serialized down to the browser with a value of `null` since properties with a value of `undefined` are not serialized by `JSON.stringify()` and we need to keep the properties around to ensure getters and setters are attached. While we could make changes to distinguish between `null` and `undefined`, I'm not sure it is worth it.

Is there a need to distinguish between `null`/`undefined` in the state? What type of problem did you run into or did you just find it to be unexpected?

**Comment by mindeavor** [comment]
My use case was importing a function that returns `string | null`:

```js
module.exports = function gradePassword (pass) {
  var score = scorePassword(pass)

  if      (score > 80)  return 'great'
  else if (score > 60)  return 'good'
  else if (score > 0)   return 'poor'
  else                  return null
}
```

And later...

    this.state.grade = gradePassword(this.state.password)

Naturally I used triple-equals to compare the result, i.e. `<if( state.grade === null )> ... </if>`. It was quite a surprise to find the condition fail to pass.

I think it's fine and makes sense to require a non-undefined state value to serialize to the client. But converting `null` to `undefined` is quite confusing.
