### ISSUE TITLE
include-html content is not minified

### ISSUE THREAD

**Issue by yomed** [marko-js/marko#581]
## Bug Report
(Marko v3) I am currently including an SVG file via `<inlclude-html("./icon.svg")/>`. All other markup on the page is minified correctly since it is generated that way through the compiled templates, but content from `include-html` is output verbatim with whitespace.

### Expected Behavior
HTML included via `include-html` should be minified.

### Actual Behavior
HTML included via `include-html` is not minified.

### Possible Fix
Strip whitespace within the core custom tag.

<details><summary>Additional Info</summary>

### Your Environment

* Version used: Marko v3.14.2

</details>

**Comment by Hesulan** [comment]
The "minification" of Marko templates is only a side-effect of the way it renders from an AST. The `include-html` tag is designed to guarantee that the raw file content is copied directly into the output without any transformation. In other words, this is working as intended.

Marko does not contain a minifier, and even if it did it would be dangerous to assume that the included file's content is safe to minify. If the content needs to be minified then it should either be used as a Marko template (so that it gets converted to an AST), or the contents should be piped through a *true* minifier before being passed to Marko.

**Comment by yomed** [comment]
@Hesulan Thanks, I am aware that templates are "minified" through compilation. Since the actual outcome is that all HTML is minified, it seems reasonable from a product perspective that content in `include-html` would be minified as well. Since content included that way is already assumed to be HTML, I don't think it would be dangerous to minify conservatively.

`include-html` was introduced because there are other problems with having raw files (like SVG) used as Marko templates directly. Of course, I could minify the file before passing it along, but I opened this issue for clarification.

**Comment by AndyOGo** [comment]
@yomed Just pipe to kangax's [`html-minifier`](https://www.npmjs.com/package/html-minifier).
Though it's better to minify them once in a build step.
