### ISSUE TITLE
[v4] Data binding for select tag bug

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#595]
## Bug Report

This could be a morphdom issue.

### Context

```jsx
class {
  onCreate() {
    this.state = { width: 200, height: 100, color: "blue" }
  }
  choose(e) {
    this.state.color = e.target.value
  }
}

<div class="color-box" style={
    width: state.width + 'px',
    height: state.height + 'px',
    backgroundColor: state.color
  }>

  <select value=state.color on-change('choose')>
    <option value="red">Red</option>
    <option value="blue">Blue</option>
  </select>

  ${state.color}

  <br />
  <button on-click('choose') value="red">Set to Red</button>
  <br />
  <button on-click('choose') value="blue">Set to Blue</button>
</div>

```

### Expected Behavior

The `<select>` should initialize with the `blue` option selected. On setting `state.color` (such as clicking one of the two buttons), the selected option should update accordingly.

### Actual Behavior

The `<select>` initializes with the first option. When setting `state.color`, the select resets to a blank option.

<details><summary>Additional Info</summary>

### Your Environment
* Version used: v4.0.0-rc.19
* Environment name and version: Chrome 56
* Operating System and version (desktop or mobile): OS X
</details>

**Comment by patrick-steele-idem** [comment]
Looks to be not a bug in marko. `value` is not a standard HTML attribute on the `<select>` element. Instead, you should be doing the following:

```jsx
class {
  onCreate() {
    this.state = { width: 200, height: 100, color: "blue" }
  }
  choose(e) {
    this.state.color = e.target.value
  }
}

<div class="color-box" style={
    width: state.width + 'px',
    height: state.height + 'px',
    backgroundColor: state.color
  }>

  <select on-change('choose')>
    <option value="red" selected=(state.color==='red')>Red</option>
    <option value="blue" selected=(state.color==='blue')>Blue</option>
  </select>

  ${state.color}

  <br />
  <button on-click('choose') value="red">Set to Red</button>
  <br />
  <button on-click('choose') value="blue">Set to Blue</button>
</div>
```

**Comment by mindeavor** [comment]
It's true that it's not a standard tag, but neither is `on-change`, is it? :)

I expect `<select>` to behave in this manner because running `mySelectDomElement.value = 'blue'` will in fact update the `<select>` tag to select the correct option.

The `value` attribute in React.js and Mithril.js behaves in this way. Angular and Vue allow you to do their model binding directly on the `<select>` tag. It's a pattern that makes good sense.

**Comment by patrick-steele-idem** [comment]
@mindeavor We did discuss the idea of making this work after reviewing your bug report. And, while we could make it work it would add a decent amount of complexity and I'm not seeing a strong need for it. Specifically, we would need to special case the rendering of all `<option>` elements to control how the `selected` attribute gets set based on the `value` attribute on a parent `<select>` element. Even then, you would have issues if someone decided to split the rendering of `<option>` elements into a component that is separate from the parent `<select>` element. There's also complexity around making this work the same for both server-side rendering and client-side rendering since there is a mismatch between when is supported by HTML attributes and what is supported by HTML element properties.

For now, I think it is much better to stick with standard HTML element attributes which is what Marko aligns with (React and other client-side libraries use HTML element properties).

Not that it matters at this point, but it's too bad that they made this so awkward with the HTML spec :)

**Comment by mindeavor** [comment]
Makes sense, thanks for looking into it 👍
