### ISSUE TITLE
[Question] Best practice guide for production?

### ISSUE THREAD

**Issue by mauricionr** [marko-js/marko#597]
## Question

I'm using marko and is awesome

My question is, there's any Best Practice guide for production enviroment?

Thanks guys!

**Comment by Hesulan** [comment]
For client-side, see #490; The documentation is still a work-in-progress. Patrick mentioned using `minprops` and `envify` to reduce code size, but you should really just follow the standard best practices for *all* client-side code: Minify, gzip, and cache responsibly. How you actually *do* that depends on your other libraries and frameworks - `express`, `lasso`, etc.

Server-side, the only recommendation I'm aware of is to set `NODE_ENV=production`. That's because `Marko` is designed to be the best of both worlds - convenient in development, efficient in production.

**Comment by patrick-steele-idem** [comment]
Thanks for the feedback @mauricionr !

Just to add to what @Hesulan said, minification and [minprops](https://github.com/mlrawlings/minprops) (not yet documented) are the only two things that are strongly recommended for production builds. But yes, we will be publishing a guide for production builds. I'll keep this issue open as a reminder. Thanks, again!

**Comment by DylanPiercey** [comment]
The new [examples](https://github.com/marko-js/examples/) repo does have some mostly production-ready setups. Also, there is now [`@marko/serve` and `@marko/build`](https://github.com/marko-js/cli/blob/master/packages/serve/README.md) for a zero-config production-ready setup.
