### ISSUE TITLE
Cannot use CSS rule !important in style block of marko file

### ISSUE THREAD

**Issue by stephenbrady** [marko-js/marko#669]
### Context
Unable to use CSS rule `!important` in style block of marko file.

### Expected Behavior
The following is valid CSS in a marko file.
```
style {
  .foo-class {
    height: 50px !important;
  }
}
<div.foo-class/>
```
### Actual Behavior
Error when compiling:
```Module not found: Error: Can't resolve 'important;/n  }"}'```

### Your Environment

* Version used: v4.2.7

**Comment by patrick-steele-idem** [comment]
@stephenbrady thanks for opening the issue. I added a test case and I am not able to reproduce. Can you please provide more details on how to reproduce?

**Comment by austinkelleher** [comment]
This looks to only be an issue with [marko-loader](https://github.com/marko-js/marko-loader). I haven't had a chance to investigate yet, but I am able to reproduce it.

**Comment by stephenbrady** [comment]
That'd be consistent. I am using `marko-loader`.

**Comment by mlrawlings** [comment]
I think this is an issue with the way we're loading the css and how webpack interprets requires.  

Here, the inline css is passed as a query parameter to the internal code-loader:
https://github.com/marko-js/marko-loader/blob/master/src/index.js#L31-L32

But because webpack uses exclamation points in require statements as a loader syntax (`require('css!less!./path/to/style.less')`), the `!important` is throwing things off.

I'm already doing something [weird](https://github.com/marko-js/marko-loader/blob/master/src/code-loader.js#L3-L6) to handle newlines.  But replace that with a call to `escape` [here](https://github.com/marko-js/marko-loader/blob/master/src/index.js#L30) and `unescape` [here](https://github.com/marko-js/marko-loader/blob/master/src/code-loader.js#L5).

@stephenbrady Would you mind experimenting and creating a PR if things work out?

**Comment by stephenbrady** [comment]
The PR (https://github.com/marko-js/marko-loader/pull/13) that I just submitted against the `marko-loader` repo resolves this issue for me.
