### ISSUE TITLE
Remove comments / other stuff from templates on render

### ISSUE THREAD

**Issue by lostpebble** [marko-js/marko#674]
### Description
I'd like to be able to pass an option to renderToString that removes comments from that template. Perhaps also console.log calls.

### Context
Sometimes when I'm developing, especially in the view file which spits out most of my HTML page, I want to comment out / in certain sections - such as code for analytics trackers or other such things. This is so I can easily add / remove features as I develop without losing the code.

For now I mostly use Marko for server-side rendering my base HTML page which I plug another view engine (ReactJS) on top of. The ability to remove / add certain `<meta>` tags or some JavaScript on the fly using comments would be great - as these things are often changing. Right now all my pages are rendered with all the commented out sections too, which is adding to page size.

### Possible Implementation
Have an options object that can be passed to renderToString, with something like:
```
{
  removeComments: true,
  removeConsole: true
}
```

**Comment by patrick-steele-idem** [comment]
HTML-style comments are already completely removed at compile-time and should never show up in the rendered output. For example, given the following template:

```marko
<h1>
    <!-- Hello ${name}! -->
</h1>
```

The output HTML would be:

```html
<h1></h1>
```

For removing console logging statements, that could be done using babel: https://www.npmjs.com/package/babel-plugin-transform-remove-console

Typically, babel is only used when generating JavaScript bundles for the browser, but you could also use babel to preprocess JavaScript files loaded by Node.js.


If I am misunderstanding your question regarding the comments removal please let me know.

**Comment by lostpebble** [comment]
Oh, I wasn't aware that HTML-style comments were being removed. Looking back at my project I see that certain tags I commented out that way have actually been removed. That's cool.

It's mainly the JavaScript part of my code that I've been commenting out sections of - inside of HTML `<script>` tags. It seems these comments are not removed.

I might have to look at a babel solution then - although I've just tried to get rid of any babel on my server recently. When I do a `require` of the `.marko` file template, would the server know to transform the resulting JavaScript file which is generated by Marko? There doesn't seem to be a place where I actually reference the JavaScript file directly, and could potentially pass it to a babel transformer. I don't want babel to by default transform every JavaScript file because that can become a bit heavy.

**Comment by patrick-steele-idem** [comment]
Marko doesn't process HTML-style comments in `<script>` tags. Anything inside a `<script>` tag can be any language so it wouldn't make sense for Marko to fully parse out the content of a `<script>`.

I also prefer to avoid using babel on the server, but just wanted to throw it out as an option. 

When you are in "JavaScript land" (e.g. inside a JavaScript function), Marko does not have much control because we don't want Marko to get in the business of rewriting JavaScript code.

Another option is to monkey-patch the `console` object to make the `console.log` method a no-op, but this might cause issues with debugging and would not be recommended, but here it is anyway:

```js
console.log = function noop() {};
```

A better option is to pull in a logging framework with configurable loggers so that you can control logging. With that approach, you would be going through your own logger instances instead of calling `console.log` directly.

I'm going to go ahead and close this issue, but feel free to comment here if you have any other questions.
