### ISSUE TITLE
How to manage dependencies when dynamically including components

### ISSUE THREAD

**Issue by mauricionr** [marko-js/marko#689]
Hey guys,

I have a component called `<product-list />`, when i call this component inside a page everything works fine, both files are executed, `component.js` and `component-browser.js`

but when i put this component inside an `<include />` tag only the server side js is executed, and the component-browser.js file didn't come to the browser.

obs: this include is wrapped in an await tag.

how do i proceed with a component inside an include tag?

Thanks!

**Comment by hedav85** [comment]
I run into the same problem.

**Comment by patrick-steele-idem** [comment]
After giving it some thought, I'm pretty sure that this is because Lasso utilizes static code analysis to figure out what to send down to the browser. We can do static code analysis on a template to discover custom tags to figure out which JS files need to be bundled up (including `component-browser.js`), but if you are using an `<include>` tag then the include target is dynamic and static code analysis won't help. Instead, you need to explicitly add a `require('./components/my-component/component-browser`)` in a JavaScript module that is already being bundled up and sent down to the browser or you need to add the dependency in a `browser.json` (typically in the same directory as your page template):

```json
{
    "dependencies": [
        "require: ./components/my-component/component-browser"
    ]
}
```

Let us know that resolves the problem.

**Comment by mauricionr** [comment]
@patrick-steele-idem i could import the file but the events were not attached to the comonents

i've tested with this component `<incrementer />
```
/incrementer
     component.js
     index.marko
```
```JavaScript
class {
    onCreate() {
        this.state = {
            count:0
        };
    }
    increment() {
        this.state.count++;
    }
}

```

```HTML
<div>
  <h2>The current count is ${state.count}</h2>
  <button on-click('increment')>+1</button>
</div>
```

I've added this component to a page

```HTML
<html>
     <head>
          <title>Await/Include weird behavior with components</Title
     </head>
     <body>
          <incrementer />
          <await(data from Provider) arg-path="/fragment/incrementer"><!--This await is requesting an fragment and render with marko-->
              ${data.body}
          </await>
    </body>
</html>
```

```
     /routes
          /fragments
               /incrementer
```

```JavaScript
let incrementer = require('./components/incrementer')
module.exports = (req, res) => {
     incrementer.render({}, res);
}
```

i got a strange behavior after import the file with browser.json

i will create an repo to reproduce this issue

**Comment by austinkelleher** [comment]
Hey @mauricionr. Is this still an issue for you?

**Comment by mauricionr** [comment]
i will test it again this weekend @austinkelleher, and create the repo as i said a long time ago :disappointed_relieved:

**Comment by mauricionr** [comment]
@hedav85 do you have any repo reproducing this? i would like to see it

**Comment by mauricionr** [comment]
@austinkelleher still an issue, i could load the scripts as @patrick-steele-idem said, but the component is not being rendered :thinking:

the method `onCreate` is ok but `ouMount` is never called :thinking:

**Comment by mauricionr** [comment]
the component is inside an await that is requesting an page fragment

**Comment by DylanPiercey** [comment]
It is now recommended to use the [`Dynamic Component`](https://markojs.com/docs/syntax/#dynamic-components) pattern. Otherwise, this issue is bundler specific.
