### ISSUE TITLE
Typo in webpack markdown

### ISSUE THREAD

**Issue by newyork-anthonyng** [marko-js/marko#706]
## Bug Report
Typo inside the `webpack` markdown file.

### Context

```html
<!doctype html>
<html>
<body>
    <script src="static/bundle.js"/>
</body>
</html>
```
As far as I know, the `<script>` tag cannot be self-closing, and should be changed to:
```html
<script src="static/bundle.js"></script>
```
I can make a PR to fix this if this makes sense.
### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

1. 
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by patrick-steele-idem** [comment]
Hey @newyork-anthonyng, thanks for reporting the problem with the docs. Marko allows `<script/>` and I think we have gotten used to that, but you are right that we should update the docs since we are referring to a standard HTML file. If you can send a PR to update the following file that would be greatly appreciated: https://github.com/marko-js/marko/blob/master/docs/webpack.md

Thanks again!

**Comment by newyork-anthonyng** [comment]
@patrick-steele-idem Awesome. I'm starting to dig into Marko and was assuming that it supported self-closing script tags.

I created a new [PR](https://github.com/marko-js/marko/pull/707) to address this. Let me know if anything else is needed.
