### ISSUE TITLE
A question about the docs (components)

### ISSUE THREAD

**Issue by ulivz** [marko-js/marko#746]
## Docs Question

In the chapter **components** , how should I understand this word in the following?
```
Adding styles to your view is also made easy. These styles won't be output in a <style> tag as inline styles usually are, but will result in the style being externalized so it isn't duplicated should a component be used more than once on the page.
```
Whether it's a confusion of inline style and <style> tag?

**Comment by patrick-steele-idem** [comment]
Let's say you have a UI component such as the following:

`components/my-component/index.marko`:

```marko
style {
  .my-component { color: red; }
}

<div.my-component>
  Hello ${input.name}!
</div>
```

Also, let's say that UI component is used two times:

```marko
<my-component name="John" />
<my-component name="Jane" />
```

One option would be for marko to render a `<style>` tag with every rendered UI component:

```
<style>.my-component { color: red; }</style>
<div class="my-component">
  Hello John!
</div>
<style>.my-component { color: red; }</style>
<div class="my-component">
  Hello Jane!
</div>
```

Marko does _not_ do that since the CSS code would be repeated in the HTML output. Instead, we leave it up to the asset pipeline/bundler (e.g. lasso, webpack, etc.) to bundle up all of the required CSS for all of the UI components used on the page and to include a single CSS resource similar to the following:

```
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="my-page-abc123.css">
  </head>
  <body>
    <div class="my-component">
      Hello John!
    </div>
    <div class="my-component">
      Hello Jane!
    </div>
  </body>
</html>
```

That's what we were trying to say in the docs in a more concise way. Does that clarify? Any suggestions for how to improve the wording in the docs so it is less confusing?

**Comment by DylanPiercey** [comment]
Closing this for now.

We are still open to documentation suggestions and PR's 😄.
