### ISSUE TITLE
Misleading instructions for routing in `marko create` app

### ISSUE THREAD

**Issue by ror-y** [marko-js/marko#812]
### Context

Having started a new app using `marko create`, I followed the instructions for setting up a new route:

![screen shot 2017-08-22 at 22 16 09](https://user-images.githubusercontent.com/10364894/29587922-731f1fa6-8787-11e7-8cab-6cd2a779f66f.png)

When I followed these instructions, my app broke.

Here is the error I got after creating a new route folder called `new` as per the instructions:
```
/Users/rorysmith/code/hello-world/node_modules/routes-table/index.js:112
          throw e;
          ^

Error: A route must contain a `route.js` file that exports a template or handler, or the route must contain an `index.marko` file.
At: /Users/rorysmith/code/hello-world/src/routes/new
    at Object.onRoute (/Users/rorysmith/code/hello-world/node_modules/marko-starter/src/util/loadFilesystemRoutes.js:33:17)
    at buildRoute (/Users/rorysmith/code/hello-world/node_modules/routes-table/index.js:160:37)
    at fs.stat (/Users/rorysmith/code/hello-world/node_modules/routes-table/index.js:106:19)
    at FSReqWrap.oncomplete (fs.js:114:15)
App stopped unexpectedly
```

### Expected Behavior

A new route to be added to my app.

### Actual Behavior

Error in console, `routes` page breaks.

### Possible Fix

Clearer instructions for setting up a new route
<details><summary>Additional Info</summary>

### Your Environment

* Version used: 4.4.25
* Environment name and version: Chrome 60, node 5.3

### Steps to Reproduce

1. 
2. 
3. 
4. 

### Stack Trace

</details>

**Comment by austinkelleher** [comment]
@alanbuchanan The error is telling you that you should either have a `route.js` or an `index.marko` in the folder. Without it, we are currently throwing an error, which is killing the app. Simply adding either of those files will fix your issue.

I'm thinking that maybe instead of throwing an error and killing the app, we should just write a warning with the stack trace to the console. That way, if a user creates a new folder, but hasn't yet created a `route.js` or `index.marko`, it won't kill the app.

Thoughts? 
/cc @mlrawlings @patrick-steele-idem

**Comment by mlrawlings** [comment]
A warning would probably be better

**Comment by patrick-steele-idem** [comment]
Agreed. Let's add a warning.

**Comment by alanbuchanan** [comment]
@mlrawlings That would be great.

**Comment by DylanPiercey** [comment]
@marko/create has been rewritten since this issue and it's no longer applicable.
