### ISSUE TITLE
Allow unescaped attributes

### ISSUE THREAD

**Issue by cantoine** [marko-js/marko#852]
## Feature discussion
Marko provides a way to insert unescaped html into the page `$!{...}`.  Perhaps it should support something for unescaped attributes as well.

## Original bug report

I'm seeing a double encoding issue happen in the href attr of anchors.

A super simple replication:
`<a href="https://www.something.com?param1=value&amp;param2=value2">Link</a>`

This doesn't happen if a template just has &amp; some where in the html so it appears to be related to parsing that is happening for the href.

### Expected Behavior
`<a href="https://www.something.com?param1=value&amp;param2=value2">Link</a>`

### Actual Behavior
`<a href="https://www.something.com?param1=value&amp;amp;param2=value2">Link</a>`

<details><summary>Additional Info</summary>
### Your Environment
* Version used: 4.4.28
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 6.11
</details>

I could be missing something really stupid here so forgive me if I am.

Thanks!
Chris

**Comment by patrick-steele-idem** [comment]
Hey @cantoine, thanks for opening the issue. Marko is working as expected but we probably need to do a better job describe the following behavior in our docs:

__For input:__ Marko parses all attribute values as _JavaScript_ expressions (not HTML). This means that Marko respects the JavaScript rules for encoding special characters in strings. The `&` is not a special character in JavaScript strings so it requires no special encoding.

__For output:__ Marko escapes all special HTML characters on _output_. For example, if there is an `&` character in an attribute value or in body text then it will be encoded as `&amp;`.

----

Therefore, in your example you should be writing the following in your `.marko` file:

```marko
<a href="https://www.something.com?param1=value&param2=value2">Link</a>
```

This will produce the expected output:

```html
<a href="https://www.something.com?param1=value&amp;param2=value2">Link</a>
```

We had considered decoding HTML entities in JavaScript strings, but that actually introduces more problems and I think it would make things more confusing because now the user would need to apply the encoding rules for both JavaScript and HTML. Because Marko is not decoding the `&amp;` entity at parsing time that is what gets stored in the JavaScript string and at output time the only special HTML character is the `&` character so that is what is getting encoded to produce: `&amp;amp;`.

The good news is that I think JavaScript has simpler rules for encoding special characters so less to worry about :)

I'm going to keep this issue open until we update the docs.

**Comment by cantoine** [comment]
@patrick-steele-idem thanks for the info. The example I used was a simplification of my problem.

We've built a CMS that uses marko for it's templating and we use an editor that creates links with the `&amp;` based on that being 'correct'/'valid' vs just the ampersand in the link. So then when we go to render content that was created by a user and we see the behavior I mentioned. Due to this I don't have an option of changing the value in the template without setting up parsing of the content created by the user and replacing the encoded ampersands which honestly doesn't sound fun :-).

Having said all of that I understand my use case may not match or be worth dealing with on your end  but I wanted to at least give more context to see if there was any sort of alternative option that you could think of or a way to enhance the parsing of attributes to account for what could be a special case of a url. If this is something that could be handled in some way I'm willing to help write the code to make it happen.

Thanks!
Chris

**Comment by patrick-steele-idem** [comment]
I do understand your use case a little more now. Thanks for the details. If you had control over the CMS, and if it was feasible, it would actually be better if the URLs were _not_ stored with HTML escaping applied since it is better to store those things independent of the output encoding. But if that is not something you can change then I think your best bet would be to look into how to decode those HTML encoded URLs before passing them to Marko.

**Comment by mlrawlings** [comment]
While I do think storing the unescaped urls would be better, we do provide a way to insert unescaped html into the page `$!{...}`.  Perhaps we should support something for attributes as well?

I'm going to update this issue to a feature proposal to discuss.

**Comment by cantoine** [comment]
@mlrawlings that would be a great solution for me.

For now I've had to parse the html I send to Marko. I'm not a fan of storing it unencoded because what the browser is giving me is technically correct.

I'd be willing to implement this as well, could you give me some guidance on where to start though?

Thanks!
Chris

**Comment by patrick-steele-idem** [comment]
@cantoine I still strongly believe storing the values unencoded is the best and correct thing to do. If that is not something you can do then you would need to write your own code to decode the HTML characters in the strings before passing them to Marko. You should only encode HTML characters if they are being hard coded in a standard HTML file (HTML encoding is very specific to HTML parsers and serializers). We could tell Marko to not encode the attributes on the server (since we control what HTML is sent down to the browser), but that is not something we can control in the browser because we are using the DOM API to set attribute values. For example, if you do the following:

```js
var a = document.createElement('a')
a.setAttribute('href', 'https://www.something.com?param1=value&amp;param2=value2');
a.innerHTML = 'CLICK ME';
document.body.appendChild(a);
```

Clicking the above link will take you to a URL with `&amp;` still in the URL.

You can use the [he](https://www.npmjs.com/package/he) module to do HTML decoding.

**Comment by patrick-steele-idem** [comment]
I'm closing this issue because I don't think there is anything marko can do here. If there are still concerns please feel free to add comments to let us know.
