### ISSUE TITLE
Async / Await support in component class

### ISSUE THREAD

**Issue by JarvisPrestidge** [marko-js/marko#873]
## Not sure if a bug or a feature request

Assume it's a bug because of [this issue around node 8](https://github.com/marko-js/marko/issues/837)

### Details
Trying to write asynchronous code with async / await in a component class and the marko compiler complains about the `async` keyword.

```bash
Error: An error occurred while trying to compile template at path "/home/jarvis/Projects/tasker/routes/index/components/input-form/index.marko". Error(s) in template:
1) [routes/index/components/input-form/index.marko:21:11] Unable to parse JavaScript for component class. Error: Line 21: Unexpected identifier
```

### Expected Behavior
support for async / await keywords in component class functions. I haven't been able to find any documentation about this either.

### Actual Behavior
Compiler screams.

### Example code
```javascript
class {

    ...

    async fetchTask(scanCode) {
        const response = await fetch("/badgeid", {
            method: "POST",
            body: scanCode
        });
        const body = await response.text();
        return body;
    }
}             
```

**Is this supported? And if so, what is the correct syntax for using async / await?**

p.s. Love marko :heart:

**Comment by austinkelleher** [comment]
Hey @JarvisPrestidge! Thanks for opening this issue. This issue was actually fixed in https://github.com/marko-js/marko/pull/839. Reported originally here: https://github.com/marko-js/marko/issues/837. 

The fix is currently published in the latest Marko 4 beta release (`marko@4.5.0-beta.4`). Feel free to try it out. The beta release should be officially released sometime this upcoming week.

**Comment by JarvisPrestidge** [comment]
@austinkelleher thank you so much for the reply and the heads up :thumbsup:
