### ISSUE TITLE
Dropdown value refresh for the uncontrolled component

### ISSUE THREAD

**Issue by vekannan** [marko-js/marko#954]
### Marko Version: 4.6
dsissue@5.0.0 /Users/vekannan/workout/ds/test1/dsissue
├─┬ lasso@2.11.21
│ └── marko@4.6.0  deduped
├─┬ legacy-client-ebay@1.2.0
│ └── marko@1.6.11 
└── marko@4.6.0 
### Details

I am having a dropdown (uncontrolled component)  please check the code below 

```
<select name="jiraProjectRestriction" id="jiraProjectRestriction" on-change('jprChanged') class="f_lt">
<option value="default" selected>please select value</option>
<option value="RaptorSup">RaptorSup</option>
<option value="AltusAdin">AltusAdmin</option>
</select>

```
If i change the dropdown for the first time (selecting any value other than "default" )the dropdown select the firstvalue ("default" ) . After the first action if I choose any value it selects the correct option (i.e., if i choose RaptorSup the dropdown selects RaptorSup )

### Expected Behavior
1. After the page gets rendered default should be selected as we mentioned value="default"  on page load
<option value="default" selected>please select value</option> 
2. Once I change the option to any value it should show the selected value and text rather than "defult" option 

### Actual Behavior
1. Very first time the dropdown shows the "default" option even though if we select other options in the dropdown

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

* chrome Version -->63.0.3239.84  ; Node --> v8.4.0 ; Marko --> marko@4.6.0
* Operating System and version (desktop or mobile): MAC 
* Link to your project: 

### Steps to Reproduce

1. https://github.corp.ebay.com/DeveloperSupport/dsissue/blob/master/src/pages/create-label-specification/components/content/index.marko#L167 
2. https://github.corp.ebay.com/DeveloperSupport/dsissue/blob/master/src/pages/create-label-specification/components/content/browser-doesntwork.json(please change filename to browser.json)
3. 
4. 

### Stack Trace

</details>

**Comment by ulivz** [comment]
I met this bug by too many times 😞

**Comment by DylanPiercey** [comment]
@ulivz I believe the issue for @vekannan was not an actual bug with Marko but a miss-understanding with how controlled and uncontrolled form elements work in Marko.

In Marko every form element is controlled by default. This means every time Marko renders it will force the dom properties (such as value, checked and selected) to match what is described in the template which by default is undefined. In the example above the select is controlled by Marko and has the default option selected. Every time the component is rerendered Marko will select the default option since it is what is described by the template.

You can achieve the desired output in two ways:

1. You can control the select by manually setting the selected option in the Marko template and mainting the select state in your component.

```marko
class {
  onCreate() {
    this.state = { selectedIndex: -1 };
  }

  handleSelect(e) {
    this.state.selectedIndex = e.target.selectedIndex;
  }
}

<div>
  <select onChange('handleSelect')>
    <option selected=(state.selectedIndex === -1)>Select an option</option>
    <for(item in input.items) status-var=loop>
      <option selected=(state.selectedIndex === loop.getIndex())>${item}</option>
    </for>
  </select>
</div>
```

2. You can explicitly mark the select as uncontrolled using the “no-update” attribute or a "no-update" suffix on an existing attribute (in this case one of the stateful ones like selected).

```marko
<div>
  <select>
    <option selected:no-update>Select an option</option>
    <for(item in input.items)>
      <option selected:no-update=false>${item}</option>
    </for>
  </select>
</div>
```

Typically you would want to use variant one if you need to reflect the state of the select (or input) somewhere in your component since it's state is made available within the template.

You would use variant two if you are planning to manually handle the form elements in some way or are just building a simple form which will get parsed later, or submitted to a server.

Ultimately the take away is that Marko will force the dom to match the state described in the template and you have to either store that state in the component, or tell Marko to ignore sections of the Dom which you want to control yourself.

---

With all that out of the way I am not sure if there is an actual issue here or if it is simply lacking some documentation (why I left the issue open). Please feel free to comment back if I've missed the mark.
