### ISSUE TITLE
Please update the CHANGELOG.md

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#955]
The latest release in the changelog is 4.5.3 

There are the following releases in github 
v4.7.4
v4.7.3
v4.7.2
v4.7.1
v4.7.0
v4.6.0
v4.5.6
v4.5.5
v4.5.4

In particular It would be nice to know what the breaking changes are between 4.5 and 4.6 and 4.7

**Comment by austinkelleher** [comment]
Hey @cameronbraid. We definitely need to update the changelog. I will try to get this today. There were no breaking changes intended, but there were some bugs introduced that may have broken some things. We are working on pushing out some fixes for these bugs.

**Comment by jasonmacdonald** [comment]
I've been away on another project for a while and just getting back to the project where we use Marko. I have absolutely no idea what has changed since the version we are currently using (4.5.3). Seems strange that so many releases have happen with no indication what was added/removed/fixed :( Is there a blog post or anything?

**Comment by austinkelleher** [comment]
The changelog should be up to date now. Let us know if you have any additional questions. Thanks!
