### ISSUE TITLE
component.detach is not defined

### ISSUE THREAD

**Issue by Beng89** [marko-js/marko#999]
### Details

I am building a single page app that is rendered completely in the browser. As part of this app I am building a router to handle switching views and handling urls. I would like to re-use views and one way that I was going to do this was via component.detach. However, component.detach is not defined. 

### Expected Behavior
When invoking component.detach, I expect the component's element to be detached from the DOM and not throw an exception.

### Actual Behavior
When attempting to invoke the detach function I get the following TypeError: "Uncaught TypeError: this.component.detach is not a function". After inspecting the prototype of the component I can see that detach is not defined. ___detach is defined and has the correct behavior (detaches the component's element from the DOM).

### Possible Fix
It seems like detach is not being defined correctly on the prototype. When inspecting the component, ___detach is defined and invoking it has the expected behavior of detach.

### Your Environment
Environment Name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
Operating System: Mac OS High Sierra version 10.13.3

### Stack Trace
route.ts:24 Uncaught TypeError: this.component.detach is not a function
    at HomeRoute.clearComponent (route.ts:24)
    at HomeRoute.deactivate (route.ts:34)
    at Router.navigate (router.ts:145)
    at HomeRoute.navigate (route.ts:51)
    at Component.component.on (route.ts:20)
    at invokeListener (index.js:21)
    at Component.emit (index.js:90)
    at Component.emit (Component.js:209)
    at Component.go (component.ts:4)
    at delegateEvent (event-delegation.js:53)

**Comment by jasonmacdonald** [comment]
Seems like an error in the docs. Looking at the code, there's never been a "detach" method on the component class. It's always (since August last year) been __detach (which means private).

Marko typically wants to be in charge of things like HTML elements (Virtual DOM), so I suspect trying to manual reuse something like could be dangerous and you would likely run into other "bugs" trying to override that. 

Is there a reason you are concerned with trying to manually reuse components rather than just letting Marko handle that for you? Is rerendering the viewing on a route change that expensive? If you are trying to avoid things like calling the backend again when switching back to a view, you should probably store that in a model outside the view, so you can just pass the model back in and let Marko render it. Rendering is very fast.

**Comment by Beng89** [comment]
That makes sense.

Ultimately, that is the conclusion I came to. Let marko handle all of the details.

The documentation should probably be updated to reflect this though.
